// license:BSD-3-Clause
// copyright-holders:John Byrd
/***************************************************************************

    Zero Board Computer Templates

    Minimal CPU systems for testing and development across all architectures.
    Each ZBC includes:
    - RAM (size determined by CPU address width)
    - MC6847 VDG text display (32x16)
    - Semihosting device for file I/O, console, and time services
    - ELF loader for loading programs

    Design Philosophy:
    This module uses C++ templates to eliminate code duplication across
    CPU architectures. A single template class (zbc_state) is instantiated
    for each CPU type, with compile-time customization of clock speed
    and video RAM placement.

    The DEFINE_ZBC macro generates complete machine variants from a single
    line, creating unique classes and registering them with MAME.

    Limitations:
    - No ROM (program must be loaded via -elfload)
    - No I/O ports (memory-mapped video only)
    - Video RAM is fixed at calculated address (may conflict with some programs)

    Usage:
    mame zbcm6502 -elfload program.elf
    mame zbcz80 -elfload program.elf
    mame zbc68000 -elfload program.elf
    etc.

    The ELF loader loads PT_LOAD segments into guest memory and resets the CPU.
    The CPU starts executing via its reset vector, which must be included in
    the ELF file (via linker script).

***************************************************************************/

#include "emu.h"
#include "emupal.h"
#include "screen.h"

// ZBC logging - compile-time configurable
#ifndef ZBC_LOG_GENERAL
#define ZBC_LOG_GENERAL (1U << 0)
#endif
#ifndef ZBC_LOG_MEMORY
#define ZBC_LOG_MEMORY (1U << 1)
#endif
#ifndef ZBC_VERBOSE
#define ZBC_VERBOSE 0 // Change to enable categories
#endif

#define ZBC_LOG(...)                                                           \
	do {                                                                       \
		if (ZBC_VERBOSE & ZBC_LOG_GENERAL)                                     \
			osd_printf_verbose(__VA_ARGS__);                                   \
	} while (0)
#define ZBC_LOG_MEM(...)                                                       \
	do {                                                                       \
		if (ZBC_VERBOSE & ZBC_LOG_MEMORY)                                      \
			osd_printf_verbose(__VA_ARGS__);                                   \
	} while (0)
#define ZBC_ERROR(...) osd_printf_error(__VA_ARGS__)
#define ZBC_WARNING(...) osd_printf_warning(__VA_ARGS__)
#define ZBC_INFO(...) osd_printf_info(__VA_ARGS__)

// ============================================================================
// CPU HEADERS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.hpp"

#include "imagedev/elfload.h"
#include "m6847drv.h"
#include "machine/semihost.h"
#include "video/mc6847.h"

namespace {

#ifdef offs_t
using zbc_addr_t = offs_t; // Memory addresses (adapts to MAME)
using zbc_size_t = offs_t; // Memory sizes (adapts to MAME)
#else
using zbc_addr_t = uint64_t; // Fallback: 64-bit addresses
using zbc_size_t = uint64_t; // Fallback: 64-bit sizes
#endif
using zbc_speed_t = uint64_t; // CPU speeds (64-bit for future GHz ranges)

// Template parameters:
//   CPU_TYPE:   CPU device class (e.g., m6502_device, z80_device)
//   CPU_SPEED:  CPU clock frequency in Hz (default 10 MHz)
//   VRAM_ADDR:  Video RAM base (default 0 = auto-calculate near top of address
//   space)
template <typename CPU_TYPE, zbc_speed_t CPU_SPEED = 10'000'000,
          zbc_addr_t VRAM_ADDR = 0>
class zbc_state : public driver_device {
  public:
	zbc_state(const machine_config &mconfig, device_type type, const char *tag)
	    : driver_device(mconfig, type, tag), m_maincpu(*this, "maincpu"),
	      m_vdg(*this, "vdg"), m_semihost(*this, "semihost"),
	      m_elfload(*this, "elfload"),
	      m_videoram(*this, "videoram", 0x200, ENDIANNESS_LITTLE) {}

	template <typename DEVICE_TYPE>
	void zbc(machine_config &config, DEVICE_TYPE const &cpu_type) ATTR_COLD;

  protected:
	virtual void machine_start() override;
	virtual void machine_reset() override ATTR_COLD;

  private:
	// Devices
	required_device<cpu_device> m_maincpu;
	required_device<mc6847_base_device> m_vdg;
	required_device<semihost_device> m_semihost;
	optional_device<elfload_image_device> m_elfload;

	// Memory - byte-granular VRAM access for MC6847
	memory_share_creator<uint8_t> m_videoram;
	static constexpr zbc_size_t VRAM_SIZE = 512; // 32x16 text mode
	static constexpr zbc_size_t VRAM_MASK =
	    VRAM_SIZE - 1; // 0x1FF - mask for VRAM indexing
	static constexpr zbc_size_t SEMIHOST_SIZE = 32; // Semihost device registers


	// Console display driver
	MC6847Console m_console;

	void mem_map(address_map &map) ATTR_COLD;
	void init_screen();

	uint8_t vdg_videoram_r(offs_t offset);

	// Calculate video RAM address - placed near top of address space.
	// For n-bit space, VRAM starts at (2^n - 2^(n/2)) leaving proportional high
	// memory:
	//   16-bit (64KB):  0xFD00    24-bit (16MB):  0xFFEE00    32-bit (4GB):
	//   0xFFFEFE00
	// MUST be called only when address space exists (machine_start(), not
	// mem_map()).
	zbc_addr_t get_vram_addr() const {
		if (VRAM_ADDR != 0)
			return VRAM_ADDR;
		int addr_bits = m_maincpu->space(AS_PROGRAM).addr_width();
		zbc_addr_t reserved_start =
		    (1ULL << addr_bits) - (1ULL << (addr_bits / 2));
		return reserved_start - VRAM_SIZE;
	}

	// Calculate semihost device address - placed just before VRAM.
	// Device registers are 32 bytes, placed immediately before video RAM.
	// MUST be called only when address space exists (machine_start(), not
	// mem_map()).
	zbc_addr_t get_semihost_addr() const {
		return get_vram_addr() - SEMIHOST_SIZE;
	}

	// Format memory size in human-readable units (KB, MB, GB)
	// Returns string like "64 KB", "16 MB", "4 GB"
	std::string format_ram_size(zbc_size_t bytes) const {
		const zbc_size_t KB = 1024;
		const zbc_size_t MB = KB * 1024;
		const zbc_size_t GB = MB * 1024;

		char buf[32];
		if (bytes >= GB) {
			// Round to nearest GB: add GB/2 before dividing
			zbc_size_t rounded = (bytes + (GB / 2)) / GB;
			snprintf(buf, sizeof(buf), "%llu GB", (unsigned long long)rounded);
		} else if (bytes >= MB) {
			// Round to nearest MB
			zbc_size_t rounded = (bytes + (MB / 2)) / MB;
			snprintf(buf, sizeof(buf), "%llu MB", (unsigned long long)rounded);
		} else if (bytes >= KB) {
			// Round to nearest KB
			zbc_size_t rounded = (bytes + (KB / 2)) / KB;
			snprintf(buf, sizeof(buf), "%llu KB", (unsigned long long)rounded);
		} else {
			snprintf(buf, sizeof(buf), "%llu bytes", (unsigned long long)bytes);
		}
		return std::string(buf);
	}
};

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::mem_map(
    address_map &map) {
	map.unmap_value_high(); // Unmapped reads return 0xFF (floating bus
	                        // behavior)

	// Calculate the CPU's address mask based on its address width
	const address_space_config &config = map.get_config();
	zbc_addr_t addr_mask = (1ULL << config.addr_width()) - 1;

	// MAME's address_to_byte() size calculation overflows when mapping
	// regions where (end - start + 1) exceeds offs_t max value.
	// Split large address spaces into chunks to prevent overflow.
	// Maximum safe region size: 2GB - 1 (0x7FFFFFFF)
	constexpr zbc_addr_t MAX_SAFE_SIZE = 0x7FFFFFFF;

	zbc_size_t total_size = static_cast<zbc_size_t>(addr_mask) + 1;

	if (total_size <= MAX_SAFE_SIZE) {
		// Address space fits in single allocation
		ZBC_LOG_MEM("ZBC: Mapping 0x0-0x%llX as single RAM region\n",
		            (unsigned long long)addr_mask);
		map(0, addr_mask).ram();
	} else {
		// Split into 2GB chunks to avoid overflow in MAME's size calculation
		ZBC_LOG_MEM("ZBC: Splitting large address space into 2GB chunks\n");
		zbc_addr_t current_start = 0;
		while (current_start <= addr_mask) {
			zbc_addr_t chunk_end = current_start + MAX_SAFE_SIZE;
			if (chunk_end > addr_mask)
				chunk_end = addr_mask;

			ZBC_LOG_MEM("ZBC:   Chunk 0x%llX-0x%llX\n",
			            (unsigned long long)current_start,
			            (unsigned long long)chunk_end);
			map(current_start, chunk_end).ram();

			// Check for wrap-around before incrementing
			if (chunk_end == addr_mask)
				break;

			current_start = chunk_end + 1;
		}
	}

	// VRAM will be installed over these regions in machine_start() with
	// specific backing storage
}

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
uint8_t zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::vdg_videoram_r(
    offs_t offset) {
	// MC6847 VDG reads character codes from video RAM for display.
	// Called ~15,000 times/second as VDG scans the 32x16 character grid.
	return m_videoram[offset & VRAM_MASK]; // Mask to 512-byte range
}

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::init_screen() {
	m_console.clear_screen();

	m_console.center_line("Zero board computer");
	m_console.center_line(m_maincpu->name());
	m_console.center_line("www.zeroboardcomputer.com");
	m_console.center_line("");

	// Display memory configuration
	char addr_buf[64];
	zbc_addr_t semihost_addr = get_semihost_addr();
	zbc_addr_t vram_addr = get_vram_addr();

	snprintf(addr_buf, sizeof(addr_buf), "RAM: 0x0 - 0x%llX",
	         (unsigned long long)(semihost_addr - 1));
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Semihost: 0x%llX-0x%llX",
	         (unsigned long long)semihost_addr,
	         (unsigned long long)(semihost_addr + SEMIHOST_SIZE - 1));
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Video RAM: 0x%llX-0x%llX",
	         (unsigned long long)vram_addr,
	         (unsigned long long)(vram_addr + VRAM_SIZE - 1));
	m_console.center_line(addr_buf);

	m_console.center_line("");

	// Display welcome message with RAM size
	std::string ram_size_str = format_ram_size(semihost_addr);
	std::string intro = "This system has " + ram_size_str +
	                    " of RAM and a MC6847 video display. "
	                    "Load and execute an ELF executable in MAME "
	                    "by using the -elfload option. "
	                    "Happy coding!";
	m_console.print_sentence(intro.c_str());
}

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::machine_start() {
	// RUNTIME MEMORY INSTALLATION:
	// NOW devices have started and address spaces exist. We can query CPU
	// properties and install memory dynamically based on the actual hardware
	// capabilities.

	// === Validation: Check CPU has program space ===
	if (!m_maincpu) {
		ZBC_ERROR("ZBC machine_start: CPU device is null\n");
		return;
	}

	if (!m_maincpu->has_space(AS_PROGRAM)) {
		ZBC_ERROR("ZBC machine_start: CPU '%s' has no AS_PROGRAM space\n",
		          m_maincpu->name());
		ZBC_ERROR("  Possible reasons:\n");
		ZBC_ERROR("    - CPU has internal memory management (not "
		          "compatible with ZBC)\n");
		ZBC_ERROR(
		    "    - Harvard architecture with separate program/data spaces\n");
		ZBC_ERROR("    - Device is not actually a CPU\n");
		ZBC_ERROR(
		    "  Action: Mark as 'disabled' or 'not_cpu' in zbc_status.csv\n");
		return;
	}

	address_space &space = m_maincpu->space(AS_PROGRAM);

	// === Query CPU address space properties ===
	const int addr_bits = space.addr_width();
	const zbc_addr_t addr_mask = space.addrmask();
	const zbc_size_t addr_space_size = addr_mask + 1;

	// === Calculate VRAM address ===
	const zbc_addr_t vram_addr = get_vram_addr();
	const zbc_addr_t vram_end = vram_addr + VRAM_SIZE - 1;

	// === Validate address space is large enough ===
	const zbc_size_t min_program = 2048; // Minimum program space
	const zbc_size_t min_required = min_program + SEMIHOST_SIZE + VRAM_SIZE;

	if (addr_space_size < min_required) {
		ZBC_ERROR("ZBC machine_start: CPU '%s' address space too small\n",
		          m_maincpu->name());
		ZBC_ERROR("  Address space: 0x%X (%d-bit)\n", addr_space_size,
		          addr_bits);
		ZBC_ERROR("  Minimum required: 0x%X\n", min_required);
		ZBC_ERROR("  Action: Mark as 'disabled' in zbc_status.csv\n");
		return;
	}

	// === Calculate semihost device address ===
	const zbc_addr_t semihost_addr = get_semihost_addr();
	const zbc_addr_t semihost_end = semihost_addr + SEMIHOST_SIZE - 1;

	// === Install semihost device registers ===
	ZBC_LOG_MEM("ZBC: Installing semihost device registers\n");
	ZBC_LOG_MEM("  Range: 0x%llX - 0x%llX\n", (unsigned long long)semihost_addr,
	            (unsigned long long)semihost_end);
	space.install_readwrite_handler(
	    semihost_addr, semihost_end,
	    read8sm_delegate(*m_semihost, FUNC(semihost_device::read)),
	    write8sm_delegate(*m_semihost, FUNC(semihost_device::write)));

	// === Install VRAM over the generic RAM from mem_map() ===
	// CRITICAL: Must use install_ram()/install_rom() to force byte-granular
	// access on 16/32-bit CPUs. The MC6847 VDG always reads bytes, but
	// map().ram() creates CPU-width memory which would cause access issues.
	if (m_elfload && m_elfload->exists()) {
		ZBC_LOG_MEM("ZBC: Installing VRAM as R/W (ELF loaded)\n");
		ZBC_LOG_MEM("  Range: 0x%llX - 0x%llX\n", (unsigned long long)vram_addr,
		            (unsigned long long)vram_end);
		space.install_ram(vram_addr, vram_end, m_videoram.target());
	} else {
		ZBC_LOG_MEM("ZBC: Installing VRAM as ROM (boot message protected)\n");
		ZBC_LOG_MEM("  Range: 0x%llX - 0x%llX\n", (unsigned long long)vram_addr,
		            (unsigned long long)vram_end);
		space.install_rom(vram_addr, vram_end, m_videoram.target());
	}

	// === Log complete memory map for debugging ===
	ZBC_LOG_MEM("\nZBC Complete Memory Map (%d-bit %s):\n", addr_bits,
	            m_maincpu->name());
	ZBC_LOG_MEM("  0x%llX - 0x%llX: RAM (0x%llX bytes)\n",
	            (unsigned long long)0, (unsigned long long)(semihost_addr - 1),
	            (unsigned long long)semihost_addr);
	ZBC_LOG_MEM("  0x%llX - 0x%llX: Semihost device (%d bytes)\n",
	            (unsigned long long)semihost_addr,
	            (unsigned long long)semihost_end, SEMIHOST_SIZE);
	ZBC_LOG_MEM("  0x%llX - 0x%llX: Video RAM (%d bytes)\n",
	            (unsigned long long)vram_addr, (unsigned long long)vram_end,
	            VRAM_SIZE);
	if (vram_end < addr_space_size - 1) {
		ZBC_LOG_MEM("  0x%llX - 0x%llX: RAM (0x%llX bytes)\n",
		            (unsigned long long)(vram_end + 1),
		            (unsigned long long)(addr_space_size - 1),
		            (unsigned long long)(addr_space_size - vram_end - 1));
	}
	ZBC_LOG_MEM(
	    "  Total RAM: 0x%llX bytes\n\n",
	    (unsigned long long)(addr_space_size - SEMIHOST_SIZE - VRAM_SIZE));

	// Initialize console with VRAM pointer
	m_console.set_vram_base(m_videoram.target());
}

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::machine_reset() {
	init_screen();
}

template <typename CPU_TYPE, zbc_speed_t CPU_SPEED, zbc_addr_t VRAM_ADDR>
template <typename DEVICE_TYPE>
void zbc_state<CPU_TYPE, CPU_SPEED, VRAM_ADDR>::zbc(
    machine_config &config, DEVICE_TYPE const &cpu_type) {
	cpu_type(config, m_maincpu, CPU_SPEED);
	m_maincpu->set_addrmap(AS_PROGRAM, &zbc_state::mem_map);

	SCREEN(config, "screen", SCREEN_TYPE_RASTER);

	MC6847(config, m_vdg, 4.433619_MHz_XTAL, true); // PAL mode
	m_vdg->set_screen("screen");
	m_vdg->input_callback().set(FUNC(zbc_state::vdg_videoram_r));

	// Semihosting device - provides file I/O, console, time services, and
	// timer interrupts. Guest programs configure timer via SYS_TIMER_CONFIG
	// syscall, acknowledge interrupts by writing 0 to STATUS register.
	SEMIHOST(config, m_semihost, 0);
	m_semihost->set_cpu_tag("maincpu");
	// Timer interrupt on IRQ0 - guest configures rate via SYS_TIMER_CONFIG
	m_semihost->irq_callback().set_inputline(m_maincpu, INPUT_LINE_IRQ0);

	ELFLOAD(config, "elfload").set_cpu(m_maincpu);
}

} // anonymous namespace

// ============================================================================
// INPUT_PORTS - Shared configuration for all ZBC variants
// ============================================================================
static INPUT_PORTS_START(zbc)
	// No hardware jumpers - all configuration via semihosting syscalls
INPUT_PORTS_END

// ============================================================================
// DEFINE_ZBC Macro - Generates complete ZBC variant in a single line
// ============================================================================
//
// This macro generates:
// 1. A derived class (zbc_<name>_state) inheriting from zbc_state template
// 2. ROM definition (empty for these systems)
// 3. MAME machine registration (makes it available via command line)
//
// Parameters:
//   cpu_class: CPU device class for template instantiation (e.g., m6502_device)
//   cpu_type: MAME device type macro for machine_config (e.g., M6502)
//   short_name: Machine name suffix, creates "zbc<short_name>" (e.g., 6502 →
//   zbc6502) display_name: Human-readable name for UI (e.g., "MOS 6502")
//   ...: Optional template parameter overrides (cpu_speed, vram_addr)
//        Example: DEFINE_ZBC(..., ..., ..., ..., 8000000) overrides CPU_SPEED=8MHz
#define DEFINE_ZBC(cpu_class, cpu_type, short_name, display_name, ...)         \
	namespace {                                                                \
	class zbc_##short_name##_state                                             \
	    : public zbc_state<cpu_class, ##__VA_ARGS__> {                         \
	  public:                                                                  \
		using zbc_state<cpu_class, ##__VA_ARGS__>::zbc_state;                  \
		void machine_config(machine_config &config) { zbc(config, cpu_type); } \
	};                                                                         \
	}                                                                          \
	ROM_START(zbc##short_name)                                                 \
	ROM_END                                                                    \
                                                                               \
	COMP(2025, zbc##short_name, 0, 0, machine_config, zbc,                     \
	     zbc_##short_name##_state, empty_init, "MAME",                         \
	     "Zero Board Computer - " display_name,                                \
	     MACHINE_NO_SOUND_HW | MACHINE_SUPPORTS_SAVE)

// ============================================================================
// CPU DEFINITIONS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.ipp"
