// license:BSD-3-Clause
// copyright-holders:John Byrd
/***************************************************************************

    Zero Board Computer Templates

    Minimal CPU systems for testing and development across all architectures.
    Each ZBC includes:
    - RAM (size determined by CPU address width)
    - MC6847 VDG text display (32x16)
    - Quickload support for loading programs

    Design Philosophy:
    This module uses C++ templates to eliminate code duplication across
    CPU architectures. A single template class (zbc_state) is instantiated
    for each CPU type, with compile-time customization of load address,
    clock speed, and video RAM placement.

    The DEFINE_ZBC macro generates complete machine variants from a single
    line, creating unique classes and registering them with MAME.

    Limitations:
    - No ROM (program must be loaded via -quik)
    - No I/O ports (memory-mapped video only)
    - Video RAM is fixed at calculated address (may conflict with some programs)

    Usage:
    mame zbc6502 -quik program.bin
    mame zbcz80 -quik program.bin
    mame zbc68000 -quik program.bin
    etc.

    The program will be loaded at a dynamically calculated address based on
    CPU address space width (formula: 2^(1 + addr_bits/2)) and executed.

***************************************************************************/

#include "emu.h"
#include "emupal.h"
#include "screen.h"

// ============================================================================
// CPU HEADERS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.hpp"

#include "imagedev/snapquik.h"
#include "m6847drv.h"
#include "machine/semihost.h"
#include "video/mc6847.h"

namespace {

#ifdef offs_t
using zbc_addr_t = offs_t;      // Memory addresses (adapts to MAME)
using zbc_size_t = offs_t;      // Memory sizes (adapts to MAME)
#else
using zbc_addr_t = uint64_t;    // Fallback: 64-bit addresses
using zbc_size_t = uint64_t;    // Fallback: 64-bit sizes
#endif
using zbc_speed_t = uint64_t;   // CPU speeds (64-bit for future GHz ranges)

// Template parameters:
//   CPU_TYPE:   CPU device class (e.g., m6502_device, z80_device)
//   LOAD_ADDR:  Quickload program load address (default 0 = auto-calculate)
//   CPU_SPEED:  CPU clock frequency in Hz (default 10 MHz)
//   VRAM_ADDR:  Video RAM base (default 0 = auto-calculate near top of address space)
template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR = 0,
          zbc_speed_t CPU_SPEED = 10'000'000, zbc_addr_t VRAM_ADDR = 0>
class zbc_state : public driver_device {
  public:
	zbc_state(const machine_config &mconfig, device_type type, const char *tag)
	    : driver_device(mconfig, type, tag), m_maincpu(*this, "maincpu"),
	      m_vdg(*this, "vdg"), m_semihost(*this, "semihost"),
	      m_quickload(*this, "quickload"),
	      m_videoram(*this, "videoram", 0x200, ENDIANNESS_LITTLE) {}

	template <typename DEVICE_TYPE>
	void zbc(machine_config &config, DEVICE_TYPE const &cpu_type) ATTR_COLD;

  protected:
	virtual void machine_start() override;
	virtual void machine_reset() override ATTR_COLD;

  private:
	// Devices
	required_device<cpu_device> m_maincpu;
	required_device<mc6847_base_device> m_vdg;
	required_device<semihost_device> m_semihost;
	optional_device<quickload_image_device> m_quickload;

	// Memory - byte-granular VRAM access for MC6847
	memory_share_creator<uint8_t> m_videoram;
	static constexpr zbc_size_t VRAM_SIZE = 512;  // 32x16 text mode
	static constexpr zbc_size_t VRAM_MASK = VRAM_SIZE - 1;  // 0x1FF - mask for VRAM indexing
	static constexpr zbc_size_t SEMIHOST_SIZE = 32;  // Semihost device registers

	// VSync interrupt configuration (JP1 jumper)
	bool m_vsync_interrupt_enabled = false;
	int m_interrupt_line = INPUT_LINE_IRQ0;

	// Console display driver
	MC6847Console m_console;

	void mem_map(address_map &map) ATTR_COLD;
	void init_screen();

	DECLARE_QUICKLOAD_LOAD_MEMBER(quickload_cb);
	bool set_pc_generically(zbc_addr_t addr);

	uint8_t vdg_videoram_r(offs_t offset);
	void vdg_fsync(int state);

	// Calculate video RAM address - placed near top of address space.
	// For n-bit space, VRAM starts at (2^n - 2^(n/2)) leaving proportional high memory:
	//   16-bit (64KB):  0xFD00    24-bit (16MB):  0xFFEE00    32-bit (4GB):  0xFFFEFE00
	// MUST be called only when address space exists (machine_start(), not mem_map()).
	zbc_addr_t get_vram_addr() const {
		if (VRAM_ADDR != 0)
			return VRAM_ADDR;
		int addr_bits = m_maincpu->space(AS_PROGRAM).addr_width();
		zbc_addr_t reserved_start = (1ULL << addr_bits) - (1ULL << (addr_bits / 2));
		return reserved_start - VRAM_SIZE;
	}

	// Calculate load address - placed proportionally in address space.
	// For n-bit space, load at 2^(1 + n/2):
	//   16-bit (64KB):  0x200     24-bit (16MB):  0x2000      32-bit (4GB):  0x20000
	// MUST be called only when address space exists (machine_start(), not mem_map()).
	zbc_addr_t get_load_addr() const {
		if (LOAD_ADDR != 0)
			return LOAD_ADDR;
		int addr_bits = m_maincpu->space(AS_PROGRAM).addr_width();
		return (1ULL << (1 + addr_bits / 2));
	}

	// Calculate semihost device address - placed just before VRAM.
	// Device registers are 32 bytes, placed immediately before video RAM.
	// MUST be called only when address space exists (machine_start(), not mem_map()).
	zbc_addr_t get_semihost_addr() const {
		return get_vram_addr() - SEMIHOST_SIZE;
	}

	// Format memory size in human-readable units (KB, MB, GB)
	// Returns string like "64 KB", "16 MB", "4 GB"
	std::string format_ram_size(zbc_size_t bytes) const {
		const zbc_size_t KB = 1024;
		const zbc_size_t MB = KB * 1024;
		const zbc_size_t GB = MB * 1024;

		char buf[32];
		if (bytes >= GB) {
			// Round to nearest GB: add GB/2 before dividing
			zbc_size_t rounded = (bytes + (GB / 2)) / GB;
			snprintf(buf, sizeof(buf), "%llu GB", (unsigned long long)rounded);
		} else if (bytes >= MB) {
			// Round to nearest MB
			zbc_size_t rounded = (bytes + (MB / 2)) / MB;
			snprintf(buf, sizeof(buf), "%llu MB", (unsigned long long)rounded);
		} else if (bytes >= KB) {
			// Round to nearest KB
			zbc_size_t rounded = (bytes + (KB / 2)) / KB;
			snprintf(buf, sizeof(buf), "%llu KB", (unsigned long long)rounded);
		} else {
			snprintf(buf, sizeof(buf), "%llu bytes", (unsigned long long)bytes);
		}
		return std::string(buf);
	}
};

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::mem_map(
    address_map &map) {
	map.unmap_value_high(); // Unmapped reads return 0xFF (floating bus
	                        // behavior)

	// Calculate the CPU's address mask based on its address width
	const address_space_config &config = map.get_config();
	zbc_addr_t addr_mask = (1ULL << config.addr_width()) - 1;

	// MAME's address_to_byte() size calculation overflows when mapping
	// regions where (end - start + 1) exceeds offs_t max value.
	// Split large address spaces into chunks to prevent overflow.
	// Maximum safe region size: 2GB - 1 (0x7FFFFFFF)
	constexpr zbc_addr_t MAX_SAFE_SIZE = 0x7FFFFFFF;

	zbc_size_t total_size = static_cast<zbc_size_t>(addr_mask) + 1;

	if (total_size <= MAX_SAFE_SIZE) {
		// Address space fits in single allocation
		osd_printf_verbose("ZBC: Mapping 0x0-0x%llX as single RAM region\n",
		                   (unsigned long long)addr_mask);
		map(0, addr_mask).ram();
	} else {
		// Split into 2GB chunks to avoid overflow in MAME's size calculation
		osd_printf_verbose("ZBC: Splitting large address space into 2GB chunks\n");
		zbc_addr_t current_start = 0;
		while (current_start <= addr_mask) {
			zbc_addr_t chunk_end = current_start + MAX_SAFE_SIZE;
			if (chunk_end > addr_mask)
				chunk_end = addr_mask;

			osd_printf_verbose("ZBC:   Chunk 0x%llX-0x%llX\n",
			                   (unsigned long long)current_start,
			                   (unsigned long long)chunk_end);
			map(current_start, chunk_end).ram();

			// Check for wrap-around before incrementing
			if (chunk_end == addr_mask)
				break;

			current_start = chunk_end + 1;
		}
	}

	// VRAM will be installed over these regions in machine_start() with
	// specific backing storage
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
uint8_t zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::vdg_videoram_r(
    offs_t offset) {
	// MC6847 VDG reads character codes from video RAM for display.
	// Called ~15,000 times/second as VDG scans the 32x16 character grid.
	return m_videoram[offset & VRAM_MASK]; // Mask to 512-byte range
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::vdg_fsync(
    int state) {
	// MC6847 field sync callback - fires at ~60Hz (PAL: ~62Hz)
	// Only trigger interrupt on rising edge (0 -> 1 transition) if enabled
	if (!state || !m_vsync_interrupt_enabled)
		return;

	// Assert the configured interrupt line (IRQ or NMI based on JP1 jumper)
	m_maincpu->set_input_line(m_interrupt_line, ASSERT_LINE);
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::init_screen() {
	m_console.clear_screen();

	m_console.center_line("Zero board computer");
	m_console.center_line(m_maincpu->name());
	m_console.center_line("www.zeroboardcomputer.com");
	m_console.center_line("");

	// Display memory configuration
	char addr_buf[64];
	zbc_addr_t semihost_addr = get_semihost_addr();
	zbc_addr_t vram_addr = get_vram_addr();
	zbc_addr_t load_addr = get_load_addr();
	// Calculate total RAM available for programs (everything before semihost device)
	zbc_size_t available_ram = semihost_addr - load_addr;

	snprintf(addr_buf, sizeof(addr_buf), "Load address: 0x%llX",
	         (unsigned long long)load_addr);
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Available RAM: %llu bytes",
	         (unsigned long long)available_ram);
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Semihost: 0x%llX-0x%llX",
	         (unsigned long long)semihost_addr,
	         (unsigned long long)(semihost_addr + SEMIHOST_SIZE - 1));
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Video RAM: 0x%llX-0x%llX",
	         (unsigned long long)vram_addr,
	         (unsigned long long)(vram_addr + VRAM_SIZE - 1));
	m_console.center_line(addr_buf);

	m_console.center_line("");

	// Display welcome message with RAM size
	std::string ram_size_str = format_ram_size(available_ram);
	std::string intro = "This system has " + ram_size_str +
	                    " of RAM and a MC6847 video display. "
	                    "Load and execute a headerless binary in MAME "
	                    "by using the -quik option. "
	                    "Happy coding!";
	m_console.print_sentence(intro.c_str());
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::machine_start() {
	// RUNTIME MEMORY INSTALLATION:
	// NOW devices have started and address spaces exist. We can query CPU
	// properties and install memory dynamically based on the actual hardware
	// capabilities.

	// === Validation: Check CPU has program space ===
	if (!m_maincpu) {
		osd_printf_error("ZBC machine_start: CPU device is null\n");
		return;
	}

	if (!m_maincpu->has_space(AS_PROGRAM)) {
		osd_printf_error(
		    "ZBC machine_start: CPU '%s' has no AS_PROGRAM space\n",
		    m_maincpu->name());
		osd_printf_error("  Possible reasons:\n");
		osd_printf_error("    - CPU has internal memory management (not "
		                 "compatible with ZBC)\n");
		osd_printf_error(
		    "    - Harvard architecture with separate program/data spaces\n");
		osd_printf_error("    - Device is not actually a CPU\n");
		osd_printf_error(
		    "  Action: Mark as 'disabled' or 'not_cpu' in zbc_status.csv\n");
		return;
	}

	address_space &space = m_maincpu->space(AS_PROGRAM);

	// === Query CPU address space properties ===
	const int addr_bits = space.addr_width();
	const zbc_addr_t addr_mask = space.addrmask();
	const zbc_size_t addr_space_size = addr_mask + 1;

	// === Calculate VRAM address ===
	const zbc_addr_t vram_addr = get_vram_addr();
	const zbc_addr_t vram_end = vram_addr + VRAM_SIZE - 1;

	// === Validate address space is large enough ===
	const zbc_size_t min_program = 2048; // Minimum program space
	const zbc_size_t min_required = min_program + SEMIHOST_SIZE + VRAM_SIZE;

	if (addr_space_size < min_required) {
		osd_printf_error("ZBC machine_start: CPU '%s' address space too small\n",
		                 m_maincpu->name());
		osd_printf_error("  Address space: 0x%X (%d-bit)\n", addr_space_size, addr_bits);
		osd_printf_error("  Minimum required: 0x%X\n", min_required);
		osd_printf_error("  Action: Mark as 'disabled' in zbc_status.csv\n");
		return;
	}

	// === Calculate semihost device address ===
	const zbc_addr_t semihost_addr = get_semihost_addr();
	const zbc_addr_t semihost_end = semihost_addr + SEMIHOST_SIZE - 1;

	// === Install semihost device registers ===
	osd_printf_verbose("ZBC: Installing semihost device registers\n");
	osd_printf_verbose("  Range: 0x%llX - 0x%llX\n",
	                   (unsigned long long)semihost_addr,
	                   (unsigned long long)semihost_end);
	space.install_readwrite_handler(semihost_addr, semihost_end,
	                                read8sm_delegate(*m_semihost, FUNC(semihost_device::read)),
	                                write8sm_delegate(*m_semihost, FUNC(semihost_device::write)));

	// === Install VRAM over the generic RAM from mem_map() ===
	// CRITICAL: Must use install_ram()/install_rom() to force byte-granular
	// access on 16/32-bit CPUs. The MC6847 VDG always reads bytes, but
	// map().ram() creates CPU-width memory which would cause access issues.
	if (m_quickload && m_quickload->exists()) {
		osd_printf_verbose("ZBC: Installing VRAM as R/W (quickload present)\n");
		osd_printf_verbose("  Range: 0x%llX - 0x%llX\n",
		                   (unsigned long long)vram_addr,
		                   (unsigned long long)vram_end);
		space.install_ram(vram_addr, vram_end, m_videoram.target());
	} else {
		osd_printf_verbose("ZBC: Installing VRAM as ROM (boot message protected)\n");
		osd_printf_verbose("  Range: 0x%llX - 0x%llX\n",
		                   (unsigned long long)vram_addr,
		                   (unsigned long long)vram_end);
		space.install_rom(vram_addr, vram_end, m_videoram.target());
	}

	// === Log complete memory map for debugging ===
	osd_printf_verbose("\nZBC Complete Memory Map (%d-bit %s):\n", addr_bits,
	                   m_maincpu->name());
	osd_printf_verbose("  0x%llX - 0x%llX: RAM (0x%llX bytes)\n",
	                   (unsigned long long)0,
	                   (unsigned long long)(semihost_addr - 1),
	                   (unsigned long long)semihost_addr);
	osd_printf_verbose("  0x%llX - 0x%llX: Semihost device (%d bytes)\n",
	                   (unsigned long long)semihost_addr,
	                   (unsigned long long)semihost_end,
	                   SEMIHOST_SIZE);
	osd_printf_verbose("  0x%llX - 0x%llX: Video RAM (%d bytes)\n",
	                   (unsigned long long)vram_addr,
	                   (unsigned long long)vram_end,
	                   VRAM_SIZE);
	if (vram_end < addr_space_size - 1) {
		osd_printf_verbose("  0x%llX - 0x%llX: RAM (0x%llX bytes)\n",
		                   (unsigned long long)(vram_end + 1),
		                   (unsigned long long)(addr_space_size - 1),
		                   (unsigned long long)(addr_space_size - vram_end - 1));
	}
	osd_printf_verbose("  Total RAM: 0x%llX bytes\n\n",
	                   (unsigned long long)(addr_space_size - SEMIHOST_SIZE - VRAM_SIZE));

	// Initialize console with VRAM pointer
	m_console.set_vram_base(m_videoram.target());
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::machine_reset() {
	init_screen();

	// Configure VSync interrupt based on JP1 jumper setting
	uint8_t jumper_config = ioport("CONFIG")->read() & 0x03;
	switch (jumper_config) {
	case 0x00: // Disabled (default - safe for simple programs)
		m_vsync_interrupt_enabled = false;
		break;
	case 0x01: // IRQ mode (maskable interrupts for OS development)
		m_vsync_interrupt_enabled = true;
		m_interrupt_line = INPUT_LINE_IRQ0;
		break;
	case 0x02: // NMI mode (non-maskable interrupts for OS development)
		m_vsync_interrupt_enabled = true;
		m_interrupt_line = INPUT_LINE_NMI;
		break;
	default:
		m_vsync_interrupt_enabled = false;
		break;
	}
}

/***************************************************************************
 * set_pc_generically - Set program counter using symbol name lookup
 *
 * BACKGROUND: MAME's set_pc() method doesn't work for all CPU types.
 *
 * The standard set_pc() calls set_state_int(STATE_GENPC, pc), which requires
 * the CPU to register STATE_GENPC with the .callimport() flag. When callimport
 * is present, writing to that state entry triggers state_import() which syncs
 * the value to the CPU's internal registers.
 *
 * PROBLEM: Approximately 50% of MAME's CPU implementations do NOT register
 * STATE_GENPC with callimport. For example, m6502.cpp line 59:
 *
 *     state_add(STATE_GENPC, "GENPC", XPC).callexport().noshow();
 *
 * Without callimport, set_pc() writes to a temporary variable (XPC) that is
 * never synced back to the actual program counter (NPC). The CPU continues
 * executing from its reset vector instead of the requested address.
 *
 * CPUs WITHOUT callimport on STATE_GENPC (broken set_pc):
 *   m6502, w65c02, r65c02, m65c02, arm7, superfx, mips3, i960, e132xs, etc.
 *
 * CPUs WITH callimport on STATE_GENPC (working set_pc):
 *   z80, m68000, sh2, sh4, g65816, m6809, cosmac, etc.
 *
 * SOLUTION: All CPUs register their native "PC" register with callimport.
 * For m6502.cpp line 62:
 *
 *     state_add(M6502_PC, "PC", NPC).callimport();
 *
 * By looking up the state entry with symbol "PC" and writing directly to it,
 * we bypass the broken STATE_GENPC mechanism and use the CPU's working
 * native PC register.
 *
 * This function iterates through state_entries(), finds the entry with
 * symbol() == "PC", and calls set_value() on it.
 *
 * HISTORY: The m6502 STATE_GENPC was changed in commit 38306e6b274 (Feb 2018)
 * from pointing to NPC (actual PC) to XPC (temp variable) to support
 * pc_to_external() translation for banked memory variants. The author added
 * callexport for reading but forgot callimport for writing.
 *
 * Returns true if PC was set, false if no writeable "PC" register was found.
 ***************************************************************************/
template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
bool zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::set_pc_generically(
    zbc_addr_t addr) {
	for (auto &entry : m_maincpu->state_entries()) {
		if (entry->symbol() && strcmp(entry->symbol(), "PC") == 0) {
			if (entry->writeable()) {
				entry->set_value(addr);
				return true;
			}
			osd_printf_error("ZBC: PC register found but not writeable\n");
			return false;
		}
	}
	osd_printf_error("ZBC: No PC register found in CPU state entries\n");
	return false;
}

// Quickload callback: Load binary program into memory
// Called when user specifies -quik program.bin on command line.
// Loads raw binary at LOAD_ADDR and prepares system for execution.
template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
std::pair<std::error_condition, std::string>
zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::quickload_cb(
    snapshot_image_device &image) {
	// Check if CPU has program address space before loading
	if (!m_maincpu || !m_maincpu->has_space(AS_PROGRAM)) {
		osd_printf_error("ZBC quickload_cb: CPU '%s' has no AS_PROGRAM space, "
		                 "cannot load program\n",
		                 m_maincpu ? m_maincpu->name() : "null");
		return std::make_pair(image_error::UNSPECIFIED,
		                      "CPU has no program address space");
	}

	const zbc_size_t size = image.length();
	const zbc_addr_t semihost_addr = get_semihost_addr();
	const zbc_addr_t load_addr = get_load_addr();

	// Validate program fits between load address and semihost device
	if (size > semihost_addr - load_addr)
		return std::make_pair(image_error::INVALIDLENGTH, "Program too large");

	// Read into temporary buffer (can't read directly to fragmented address
	// space)
	std::vector<uint8_t> program(size);
	if (image.fread(&program[0], size) != size)
		return std::make_pair(image_error::UNSPECIFIED,
		                      "Failed to read program file");

	// Write program to memory byte-by-byte (handles endianness/bus width)
	address_space &space = m_maincpu->space(AS_PROGRAM);
	for (zbc_addr_t i = 0; i < size; i++)
		space.write_byte(load_addr + i, program[i]);

	// Clear screen to remove boot message
	init_screen();

	// Set PC to start of loaded program
	// Use set_pc_generically() because set_pc() doesn't work on all CPU types
	osd_printf_info("ZBC quickload: loaded %llu bytes at 0x%llX, setting PC to 0x%llX\n",
	                (unsigned long long)size,
	                (unsigned long long)load_addr,
	                (unsigned long long)load_addr);

	if (!set_pc_generically(load_addr)) {
		osd_printf_warning("ZBC: set_pc_generically failed, falling back to set_pc\n");
		m_maincpu->set_pc(load_addr);
	}

	return std::make_pair(std::error_condition(), std::string()); // Success
}

template <typename CPU_TYPE, zbc_addr_t LOAD_ADDR, zbc_speed_t CPU_SPEED,
          zbc_addr_t VRAM_ADDR>
template <typename DEVICE_TYPE>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::zbc(
    machine_config &config, DEVICE_TYPE const &cpu_type) {
	cpu_type(config, m_maincpu, CPU_SPEED);
	m_maincpu->set_addrmap(AS_PROGRAM, &zbc_state::mem_map);

	SCREEN(config, "screen", SCREEN_TYPE_RASTER);

	MC6847(config, m_vdg, 4.433619_MHz_XTAL, true); // PAL mode
	m_vdg->set_screen("screen");
	// VSync field sync - optionally drives CPU interrupt based on JP1 jumper
	m_vdg->fsync_wr_callback().set(FUNC(zbc_state::vdg_fsync));
	m_vdg->input_callback().set(FUNC(zbc_state::vdg_videoram_r));

	// Semihosting device - provides file I/O, console, and time services
	// Guest programs write RIFF buffer address to RIFF_PTR, then trigger DOORBELL
	SEMIHOST(config, m_semihost, 0);
	m_semihost->set_cpu_tag("maincpu");
	// Semihost completion IRQ on IRQ1 (separate from VSync on IRQ0/NMI)
	// IRQ is disabled by default - guest must enable via IRQ_ENABLE register
	m_semihost->irq_callback().set_inputline(m_maincpu, INPUT_LINE_IRQ1);

	QUICKLOAD(config, "quickload", "bin")
	    .set_load_callback(FUNC(zbc_state::quickload_cb));
}

} // anonymous namespace

// ============================================================================
// INPUT_PORTS - Shared configuration for all ZBC variants
// ============================================================================
static INPUT_PORTS_START(zbc)
	PORT_START("CONFIG")
	PORT_CONFNAME(0x03, 0x00, "JP1: VSync Interrupt")
	PORT_CONFSETTING(   0x00, "Disabled")
	PORT_CONFSETTING(   0x01, "IRQ")
	PORT_CONFSETTING(   0x02, "NMI")
INPUT_PORTS_END

// ============================================================================
// DEFINE_ZBC Macro - Generates complete ZBC variant in a single line
// ============================================================================
//
// This macro generates:
// 1. A derived class (zbc_<name>_state) inheriting from zbc_state template
// 2. ROM definition (empty for these systems)
// 3. MAME machine registration (makes it available via command line)
//
// Parameters:
//   cpu_class: CPU device class for template instantiation (e.g., m6502_device)
//   cpu_type: MAME device type macro for machine_config (e.g., M6502)
//   short_name: Machine name suffix, creates "zbc<short_name>" (e.g., 6502 → zbc6502)
//   display_name: Human-readable name for UI (e.g., "MOS 6502")
//   ...: Optional template parameter overrides (load_addr, cpu_speed, vram_addr)
//        Example: DEFINE_ZBC(..., ..., ..., ..., 0x1000, 8000000) overrides LOAD_ADDR=0x1000, CPU_SPEED=8MHz
//        (if LOAD_ADDR not specified, defaults to 0 = auto-calculate based on address space width)
#define DEFINE_ZBC(cpu_class, cpu_type, short_name, display_name, ...)         \
	namespace {                                                                \
	class zbc_##short_name##_state                                             \
	    : public zbc_state<cpu_class, ##__VA_ARGS__> {                         \
	  public:                                                                  \
		using zbc_state<cpu_class, ##__VA_ARGS__>::zbc_state;                  \
		void machine_config(machine_config &config) { zbc(config, cpu_type); } \
	};                                                                         \
	}                                                                          \
	ROM_START(zbc##short_name)                                                 \
	ROM_END                                                                    \
	                                                                           \
	COMP(2025, zbc##short_name, 0, 0, machine_config, zbc,                     \
	     zbc_##short_name##_state, empty_init, "MAME",                         \
	     "Zero Board Computer - " display_name, MACHINE_NO_SOUND_HW | MACHINE_SUPPORTS_SAVE)

// ============================================================================
// CPU DEFINITIONS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.ipp"
