// license:BSD-3-Clause
// copyright-holders:John Byrd
/***************************************************************************

    Zero Board Computer Templates

    Minimal CPU systems for testing and development across all architectures.
    Each ZBC includes:
    - RAM (size determined by CPU address width)
    - MC6847 VDG text display (32x16)
    - Quickload support for loading programs

    Design Philosophy:
    This module uses C++ templates to eliminate code duplication across
    CPU architectures. A single template class (zbc_state) is instantiated
    for each CPU type, with compile-time customization of load address,
    clock speed, and video RAM placement. CPU-specific initialization
    (reset vectors, exception tables) is handled via template specialization.

    The DEFINE_ZBC macro generates complete machine variants from a single
    line, creating unique classes and registering them with MAME.

    Limitations:
    - No ROM (program must be loaded via -quik)
    - No I/O ports (memory-mapped video only)
    - Video RAM is fixed at calculated address (may conflict with some programs)

    Usage:
    mame zbc6502 -quik program.bin
    mame zbcz80 -quik program.bin
    mame zbc68000 -quik program.bin
    etc.

    The program will be loaded at the configured address (default 0x0200)
    and executed.

***************************************************************************/

#include "emu.h"
#include "emupal.h"
#include "screen.h"

// ============================================================================
// CPU HEADERS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.hpp"

#include "imagedev/snapquik.h"
#include "m6847drv.h"
#include "video/mc6847.h"

namespace {

// Template parameters control compile-time instantiation of CPU-specific
// variants:
//
// - CPU_TYPE: The CPU device class (e.g., m6502_device, z80_device)
//   Must be a cpu_device subclass. Used for template specialization matching
//   in init_cpu_for_idle<CPU_TYPE, LOAD_ADDR>(). Address space width is
//   queried from this device at runtime.
//
// - LOAD_ADDR: Where quickload programs are loaded (default 0x0200)
//   Default of 0x0200 avoids low memory conflicts (zero page, reset vectors).
//   Must be less than VRAM_ADDR to prevent program/video memory collision.
//
// - CPU_SPEED: CPU clock frequency in Hz (default 10 MHz)
//   Affects emulation speed but not functional behavior. MC6847 video timing
//   is independent (fixed at 4.433619 MHz PAL).
//
// - VRAM_ADDR: Video RAM base address (default 0 = auto-calculate)
//   When 0, VRAM is placed near top of address space with 256-byte gap for
//   vectors/high RAM. Explicit values override auto-calculation.
template <typename CPU_TYPE, uint32_t LOAD_ADDR = 0x0200,
          uint32_t CPU_SPEED = 10'000'000, uint32_t VRAM_ADDR = 0>
class zbc_state : public driver_device {
  public:
	zbc_state(const machine_config &mconfig, device_type type, const char *tag)
	    : driver_device(mconfig, type, tag), m_maincpu(*this, "maincpu"),
	      m_vdg(*this, "vdg"), m_quickload(*this, "quickload"),
	      m_videoram(*this, "videoram", 0x200, ENDIANNESS_LITTLE) {}

	template <typename DEVICE_TYPE>
	void zbc(machine_config &config, DEVICE_TYPE const &cpu_type) ATTR_COLD;

  protected:
	virtual void machine_start() override;
	virtual void machine_reset() override ATTR_COLD;

  private:
	required_device<cpu_device> m_maincpu;
	required_device<mc6847_base_device> m_vdg;
	optional_device<quickload_image_device> m_quickload;

	// Video RAM must be accessible as bytes regardless of CPU bus width.
	// memory_share_creator ensures 8-bit access even on 16/32-bit CPUs,
	// allowing the MC6847 VDG to read character data byte-by-byte.
	// Installed in machine_start() using install_ram() to force byte
	// granularity.
	memory_share_creator<uint8_t> m_videoram;

	// Memory region sizes - avoid magic numbers throughout code
	static constexpr offs_t VRAM_SIZE =
	    512; // MC6847 VDG 32x16 text mode requires 512 bytes

	// VSync interrupt configuration (JP1 jumper)
	bool m_vsync_interrupt_enabled = false;
	int m_interrupt_line = INPUT_LINE_IRQ0;

	// MC6847 console driver for text display
	MC6847Console m_console;

	void mem_map(address_map &map) ATTR_COLD;
	void init_screen();

	DECLARE_QUICKLOAD_LOAD_MEMBER(quickload_cb);

	uint8_t vdg_videoram_r(offs_t offset);
	void vdg_fsync(int state);

	// Format address for logging (avoids repetitive casts)
	std::string format_addr(offs_t addr) const {
		char buf[32];
		snprintf(buf, sizeof(buf), "0x%08X", addr);
		return std::string(buf);
	}

	// Calculate video RAM address.
	// VRAM placed near the top of address space, leaving room at the end.
	// For n-bit address space, VRAM starts at (2^n - 2^(n/2)) to leave
	// a proportional amount of high memory available:
	//   16-bit (64KB):  VRAM at 0xFD00 (leaves 256 bytes + VRAM at top)
	//   24-bit (16MB):  VRAM at 0xFFEE00 (leaves 4KB + VRAM at top)
	//   32-bit (4GB):   VRAM at 0xFFFEFE00 (leaves 64KB + VRAM at top)
	//
	// MUST be called only when address space exists (machine_start(), not
	// mem_map()).
	offs_t get_vram_addr() const {
		if (VRAM_ADDR != 0)
			return VRAM_ADDR; // Template parameter override

		int addr_bits = m_maincpu->space(AS_PROGRAM).addr_width();
		int half_bits = addr_bits / 2;
		offs_t reserved_start = (1ULL << addr_bits) - (1ULL << half_bits);
		return reserved_start - VRAM_SIZE;
	}

	// Format RAM size in human-readable format (e.g., "4 GB", "16 KB")
	std::string format_ram_size(offs_t bytes) const {
		const offs_t KB = 1024;
		const offs_t MB = KB * 1024;
		const offs_t GB = MB * 1024;

		char buf[32];
		if (bytes >= GB) {
			// Round to nearest GB: add GB/2 before dividing
			offs_t rounded = (bytes + (GB / 2)) / GB;
			snprintf(buf, sizeof(buf), "%u GB", rounded);
		} else if (bytes >= MB) {
			// Round to nearest MB
			offs_t rounded = (bytes + (MB / 2)) / MB;
			snprintf(buf, sizeof(buf), "%u MB", rounded);
		} else if (bytes >= KB) {
			// Round to nearest KB
			offs_t rounded = (bytes + (KB / 2)) / KB;
			snprintf(buf, sizeof(buf), "%u KB", rounded);
		} else {
			snprintf(buf, sizeof(buf), "%u bytes", bytes);
		}
		return std::string(buf);
	}
};

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::mem_map(
    address_map &map) {
	map.unmap_value_high(); // Unmapped reads return 0xFF (floating bus
	                        // behavior)

	// Calculate the CPU's address mask based on its address width
	const address_space_config &config = map.get_config();
	offs_t addr_mask = (1ULL << config.addr_width()) - 1;

	// Map entire address space as RAM
	// VRAM will be installed over this in machine_start() with specific backing
	// storage
	map(0, addr_mask).ram();
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
uint8_t zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::vdg_videoram_r(
    offs_t offset) {
	// MC6847 VDG reads character codes from video RAM for display.
	// Called ~15,000 times/second as VDG scans the 32x16 character grid.
	return m_videoram[offset & 0x1ff]; // Mask to 512-byte range
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::vdg_fsync(
    int state) {
	// MC6847 field sync callback - fires at ~60Hz (PAL: ~62Hz)
	// Only trigger interrupt on rising edge (0 -> 1 transition) if enabled
	if (!state || !m_vsync_interrupt_enabled)
		return;

	// Assert the configured interrupt line (IRQ or NMI based on JP1 jumper)
	m_maincpu->set_input_line(m_interrupt_line, ASSERT_LINE);
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::init_screen() {
	m_console.clear_screen();

	m_console.center_line("Zero board computer");
	m_console.center_line(m_maincpu->name());
	m_console.center_line("www.zeroboardcomputer.com");
	m_console.center_line("");

	// Display memory configuration
	char addr_buf[64];
	uint64_t vram_addr = get_vram_addr();
	// Calculate total RAM available for programs (everything before VRAM)
	uint64_t available_ram = vram_addr - LOAD_ADDR;

	snprintf(addr_buf, sizeof(addr_buf), "Load address: 0x%llX",
	         (unsigned long long)LOAD_ADDR);
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Available RAM: %llu bytes",
	         (unsigned long long)available_ram);
	m_console.center_line(addr_buf);

	snprintf(addr_buf, sizeof(addr_buf), "Video RAM: 0x%llX-0x%llX",
	         (unsigned long long)vram_addr,
	         (unsigned long long)(vram_addr + VRAM_SIZE - 1));
	m_console.center_line(addr_buf);

	m_console.center_line("");

	std::string ram_size_str = format_ram_size(available_ram);
	std::string intro = "This system has " + ram_size_str +
	                    " of RAM and a MC6847 video display. "
	                    "Load and execute a headerless binary in MAME "
	                    "by using the -quik option. "
	                    "Happy coding!";
	m_console.print_sentence(intro.c_str());
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::machine_start() {
	// RUNTIME MEMORY INSTALLATION:
	// NOW devices have started and address spaces exist. We can query CPU
	// properties and install memory dynamically based on the actual hardware
	// capabilities.

	// === Validation: Check CPU has program space ===
	if (!m_maincpu) {
		osd_printf_error("ZBC machine_start: CPU device is null\n");
		return;
	}

	if (!m_maincpu->has_space(AS_PROGRAM)) {
		osd_printf_error(
		    "ZBC machine_start: CPU '%s' has no AS_PROGRAM space\n",
		    m_maincpu->name());
		osd_printf_error("  Possible reasons:\n");
		osd_printf_error("    - CPU has internal memory management (not "
		                 "compatible with ZBC)\n");
		osd_printf_error(
		    "    - Harvard architecture with separate program/data spaces\n");
		osd_printf_error("    - Device is not actually a CPU\n");
		osd_printf_error(
		    "  Action: Mark as 'disabled' or 'not_cpu' in zbc_status.csv\n");
		return;
	}

	address_space &space = m_maincpu->space(AS_PROGRAM);

	// === Query CPU address space properties ===
	const int addr_bits = space.addr_width();
	const offs_t addr_mask = space.addrmask();
	const offs_t addr_space_size = addr_mask + 1;

	// === Calculate VRAM address ===
	const offs_t vram_addr = get_vram_addr();
	const offs_t vram_end = vram_addr + VRAM_SIZE - 1;

	// === Validate address space is large enough ===
	const offs_t min_program = 2048; // Minimum program space
	const offs_t min_required = min_program + VRAM_SIZE;

	if (addr_space_size < min_required) {
		osd_printf_error(
		    "ZBC machine_start: CPU '%s' address space too small\n",
		    m_maincpu->name());
		osd_printf_error("  Address space: %s (%d-bit)\n",
		                 format_ram_size(addr_space_size).c_str(), addr_bits);
		osd_printf_error("  Minimum required: %s\n",
		                 format_ram_size(min_required).c_str());
		osd_printf_error("  Action: Mark as 'disabled' in zbc_status.csv\n");
		return;
	}

	// === Install VRAM over the generic RAM from mem_map() ===
	// CRITICAL: Must use install_ram()/install_rom() to force byte-granular
	// access on 16/32-bit CPUs. The MC6847 VDG always reads bytes, but
	// map().ram() creates CPU-width memory which would cause access issues.
	if (m_quickload && m_quickload->exists()) {
		osd_printf_verbose("ZBC: Installing VRAM as R/W (quickload present)\n");
		osd_printf_verbose("  Range: %s - %s\n", format_addr(vram_addr).c_str(),
		                   format_addr(vram_end).c_str());
		space.install_ram(vram_addr, vram_end, m_videoram.target());
	} else {
		osd_printf_verbose(
		    "ZBC: Installing VRAM as ROM (boot message protected)\n");
		osd_printf_verbose("  Range: %s - %s\n", format_addr(vram_addr).c_str(),
		                   format_addr(vram_end).c_str());
		space.install_rom(vram_addr, vram_end, m_videoram.target());
	}

	// === Log complete memory map for debugging ===
	osd_printf_verbose("\nZBC Complete Memory Map (%d-bit %s):\n", addr_bits,
	                   m_maincpu->name());
	osd_printf_verbose("  %s - %s: RAM (%s)\n", format_addr(0).c_str(),
	                   format_addr(vram_addr - 1).c_str(),
	                   format_ram_size(vram_addr).c_str());
	osd_printf_verbose(
	    "  %s - %s: Video RAM (%s)\n", format_addr(vram_addr).c_str(),
	    format_addr(vram_end).c_str(), format_ram_size(VRAM_SIZE).c_str());
	if (vram_end < addr_space_size - 1) {
		osd_printf_verbose(
		    "  %s - %s: RAM (%s)\n", format_addr(vram_end + 1).c_str(),
		    format_addr(addr_space_size - 1).c_str(),
		    format_ram_size(addr_space_size - vram_end - 1).c_str());
	}
	osd_printf_verbose("  Total RAM: %s\n\n",
	                   format_ram_size(addr_space_size - VRAM_SIZE).c_str());

	// Initialize console with VRAM pointer
	m_console.set_vram_base(m_videoram.target());
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::machine_reset() {
	init_screen();

	// Configure VSync interrupt based on JP1 jumper setting
	uint8_t jumper_config = ioport("CONFIG")->read() & 0x03;
	switch (jumper_config) {
	case 0x00: // Disabled (default - safe for simple programs)
		m_vsync_interrupt_enabled = false;
		break;
	case 0x01: // IRQ mode (maskable interrupts for OS development)
		m_vsync_interrupt_enabled = true;
		m_interrupt_line = INPUT_LINE_IRQ0;
		break;
	case 0x02: // NMI mode (non-maskable interrupts for OS development)
		m_vsync_interrupt_enabled = true;
		m_interrupt_line = INPUT_LINE_NMI;
		break;
	default:
		m_vsync_interrupt_enabled = false;
		break;
	}
}

// Quickload callback: Load binary program into memory
// Called when user specifies -quik program.bin on command line.
// Loads raw binary at LOAD_ADDR and prepares system for execution.
template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
std::pair<std::error_condition, std::string>
zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::quickload_cb(
    snapshot_image_device &image) {
	// Check if CPU has program address space before loading
	if (!m_maincpu || !m_maincpu->has_space(AS_PROGRAM)) {
		osd_printf_error("ZBC quickload_cb: CPU '%s' has no AS_PROGRAM space, "
		                 "cannot load program\n",
		                 m_maincpu ? m_maincpu->name() : "null");
		return std::make_pair(image_error::UNSPECIFIED,
		                      "CPU has no program address space");
	}

	const offs_t size = image.length();
	const offs_t vram_addr = get_vram_addr();

	// Validate program fits between LOAD_ADDR and video RAM
	if (size > vram_addr - LOAD_ADDR)
		return std::make_pair(image_error::INVALIDLENGTH, "Program too large");

	// Read into temporary buffer (can't read directly to fragmented address
	// space)
	std::vector<uint8_t> program(size);
	if (image.fread(&program[0], size) != size)
		return std::make_pair(image_error::UNSPECIFIED,
		                      "Failed to read program file");

	// Write program to memory byte-by-byte (handles endianness/bus width)
	address_space &space = m_maincpu->space(AS_PROGRAM);
	for (offs_t i = 0; i < size; i++)
		space.write_byte(LOAD_ADDR + i, program[i]);

	// Clear screen to remove boot message
	init_screen();

	// Set PC to start of loaded program
	// Standard MAME quickload practice: quickload does NOT automatically set PC
	m_maincpu->set_pc(LOAD_ADDR);

	return std::make_pair(std::error_condition(), std::string()); // Success
}

template <typename CPU_TYPE, uint32_t LOAD_ADDR, uint32_t CPU_SPEED,
          uint32_t VRAM_ADDR>
template <typename DEVICE_TYPE>
void zbc_state<CPU_TYPE, LOAD_ADDR, CPU_SPEED, VRAM_ADDR>::zbc(
    machine_config &config, DEVICE_TYPE const &cpu_type) {
	cpu_type(config, m_maincpu, CPU_SPEED);
	m_maincpu->set_addrmap(AS_PROGRAM, &zbc_state::mem_map);

	SCREEN(config, "screen", SCREEN_TYPE_RASTER);

	MC6847(config, m_vdg, 4.433619_MHz_XTAL, true); // PAL mode
	m_vdg->set_screen("screen");
	// VSync field sync - optionally drives CPU interrupt based on JP1 jumper
	m_vdg->fsync_wr_callback().set(FUNC(zbc_state::vdg_fsync));
	m_vdg->input_callback().set(FUNC(zbc_state::vdg_videoram_r));

	QUICKLOAD(config, "quickload", "bin")
	    .set_load_callback(FUNC(zbc_state::quickload_cb));
}

} // anonymous namespace

// ============================================================================
// INPUT_PORTS - Shared configuration for all ZBC variants
// ============================================================================
static INPUT_PORTS_START(zbc)
	PORT_START("CONFIG")
	PORT_CONFNAME(0x03, 0x00, "JP1: VSync Interrupt")
	PORT_CONFSETTING(   0x00, "Disabled")
	PORT_CONFSETTING(   0x01, "IRQ")
	PORT_CONFSETTING(   0x02, "NMI")
INPUT_PORTS_END

// ============================================================================
// DEFINE_ZBC Macro - Generates complete ZBC variant in a single line
// ============================================================================
//
// This macro generates:
// 1. A derived class (zbc_<name>_state) inheriting from zbc_state template
// 2. ROM definition (empty for these systems)
// 3. MAME machine registration (makes it available via command line)
//
// Parameters:
//   cpu_class: CPU device class for template instantiation (e.g., m6502_device)
//   cpu_type: MAME device type macro for machine_config (e.g., M6502)
//   short_name: Machine name suffix, creates "zbc<short_name>" (e.g., 6502 → zbc6502)
//   display_name: Human-readable name for UI (e.g., "MOS 6502")
//   ...: Optional template parameter overrides (load_addr, cpu_speed, vram_addr)
//        Example: DEFINE_ZBC(..., ..., ..., ..., 0x1000, 8000000) sets LOAD_ADDR=0x1000, CPU_SPEED=8MHz
#define DEFINE_ZBC(cpu_class, cpu_type, short_name, display_name, ...)         \
	namespace {                                                                \
	class zbc_##short_name##_state                                             \
	    : public zbc_state<cpu_class, ##__VA_ARGS__> {                         \
	  public:                                                                  \
		using zbc_state<cpu_class, ##__VA_ARGS__>::zbc_state;                  \
		void machine_config(machine_config &config) { zbc(config, cpu_type); } \
	};                                                                         \
	}                                                                          \
	ROM_START(zbc##short_name)                                                 \
	ROM_END                                                                    \
	                                                                           \
	COMP(2025, zbc##short_name, 0, 0, machine_config, zbc,                     \
	     zbc_##short_name##_state, empty_init, "MAME",                         \
	     "Zero Board Computer - " display_name, MACHINE_NO_SOUND_HW | MACHINE_SUPPORTS_SAVE)

// ============================================================================
// CPU DEFINITIONS - Auto-generated by zbcgen.py
// ============================================================================
// To update: python3 scripts/build/zbcgen.py --build
#include "zbcgen.ipp"
