// Auto-generated by zbcgen.py - DO NOT EDIT
// Generated: 2026-06-12 14:00:12
// Source: src/mame/zbc/zbc_status.csv
//
// This file is #included by zbc.cpp, not compiled separately.
// Do not add #include directives here.
//
// The #line directive forces __FILE__ to resolve to zbc.cpp
// for the COMP() expansions below. MAME's GAME_DRIVER_TRAITS
// records __FILE__ as the driver's sourcefile and makedep.py
// rejects any mismatch with the @source:zbc/zbc.cpp entry in
// mame.lst.
#line 1 "src/mame/zbc/zbc.cpp"
//
// Statistics:
//   Total CPUs discovered: 391
//   working: 270
//   broken_compile: 0
//   broken_validate: 49
//   broken_header: 0
//   disabled: 4
//   not_cpu: 6
//   needs_internal_rom: 47
//   needs_dependent_device: 4
//   unknown: 0
//   Missing headers: 7

// Working CPUs (263)
// These CPUs compile and validate successfully

DEFINE_ZBC(_5a22_device, _5A22, 5a22, "Ricoh 5A22")
DEFINE_ZBC(adsp21062_device, ADSP21062, adsp21062, "Analog Devices ADSP21062 'SHARC'")
DEFINE_ZBC(am186em_device, AM186EM, am186em, "AMD Am186EM")
DEFINE_ZBC(am188em_device, AM188EM, am188em, "AMD Am188EM")
DEFINE_ZBC(arm11_cpu_device, ARM11, arm11, "ARM11")
DEFINE_ZBC(arm1176jzf_s_cpu_device, ARM1176JZF_S, arm1176jzf_s, "ARM1176JZF-S")
DEFINE_ZBC(arm710a_cpu_device, ARM710A, arm710a, "ARM710a")
DEFINE_ZBC(arm710t_cpu_device, ARM710T, arm710t, "ARM710T")
DEFINE_ZBC(arm7500_cpu_device, ARM7500, arm7500, "ARM7500")
DEFINE_ZBC(arm7_be_cpu_device, ARM7_BE, arm7_be, "ARM7 (big)")
DEFINE_ZBC(arm7_cpu_device, ARM7, arm7_le, "ARM7 (little)")
DEFINE_ZBC(arm9_cpu_device, ARM9, arm9, "ARM9")
DEFINE_ZBC(arm920t_cpu_device, ARM920T, arm920t, "ARM920T")
DEFINE_ZBC(arm946es_cpu_device, ARM946ES, arm946es, "ARM946ES")
DEFINE_ZBC(arm_cpu_device, ARM, arm_cpu, "ARM")
DEFINE_ZBC(athlonxp_device, ATHLONXP, athlonxp, "Amd Athlon XP")
DEFINE_ZBC(cdp1801_device, CDP1801, cdp1801, "RCA CDP1801")
DEFINE_ZBC(cdp1802_device, CDP1802, cdp1802, "RCA CDP1802")
DEFINE_ZBC(cdp1804_device, CDP1804, cdp1804, "RCA CDP1804")
DEFINE_ZBC(cdp1805_device, CDP1805, cdp1805, "RCA CDP1805")
DEFINE_ZBC(cdp1806_device, CDP1806, cdp1806, "RCA CDP1806")
DEFINE_ZBC(deco16_device, DECO16, deco16, "Data East DECO16")
DEFINE_ZBC(ds5002fp_device, DS5002FP, ds5002fp, "Dallas DS5002FP")
DEFINE_ZBC(ds80c320_device, DS80C320, ds80c320, "Dallas DS80C320 HSM")
DEFINE_ZBC(dsp56000_device, DSP56000, dsp56000, "Motorola DSP56000")
DEFINE_ZBC(dsp56001_device, DSP56001, dsp56001, "Motorola DSP56001")
DEFINE_ZBC(g65sc02_device, G65SC02, g65sc02, "GTE G65SC02")
DEFINE_ZBC(g65sc102_device, G65SC102, g65sc102, "GTE G65SC102")
DEFINE_ZBC(g65sc112_device, G65SC112, g65sc112, "GTE G65SC112")
DEFINE_ZBC(g65sc12_device, G65SC12, g65sc12, "GTE G65SC12")
DEFINE_ZBC(h6280_device, H6280, h6280, "Hudson Soft HuC6280")
DEFINE_ZBC(h83002_device, H83002, h83002, "Hitachi H8/3002")
DEFINE_ZBC(h83003_device, H83003, h83003, "Hitachi H8/3003")
DEFINE_ZBC(h83006_device, H83006, h83006, "Hitachi H8/3006")
DEFINE_ZBC(h83007_device, H83007, h83007, "Hitachi H8/3007")
DEFINE_ZBC(h83008_device, H83008, h83008, "Hitachi H8/3008")
DEFINE_ZBC(h83044_device, H83044, h83044, "Hitachi H8/3044")
DEFINE_ZBC(h83045_device, H83045, h83045, "Hitachi H8/3045")
DEFINE_ZBC(h83047_device, H83047, h83047, "Hitachi H8/3047")
DEFINE_ZBC(h83048_device, H83048, h83048, "Hitachi H8/3048")
DEFINE_ZBC(hd6120_device, HD6120, hd6120, "Harris HD-6120")
DEFINE_ZBC(hd6303r_cpu_device, HD6303R, hd6303r, "Hitachi HD6303R")
DEFINE_ZBC(hd6309_device, HD6309, hd6309, "Hitachi HD6309")
DEFINE_ZBC(hd6309e_device, HD6309E, hd6309e, "Hitachi HD6309E")
DEFINE_ZBC(hd64180rp_device, HD64180RP, hd64180rp, "Hitachi HD64180RP")
DEFINE_ZBC(i386_device, I386, i386, "Intel I386")
DEFINE_ZBC(i386sx_device, I386SX, i386sx, "Intel I386SX")
DEFINE_ZBC(i486_device, I486, i486, "Intel I486")
DEFINE_ZBC(i486dx4_device, I486DX4, i486dx4, "Intel I486DX4")
DEFINE_ZBC(i8008_device, I8008, i8008, "Intel 8008")
DEFINE_ZBC(i80186_cpu_device, I80186, i80186, "Intel 80186")
DEFINE_ZBC(i80188_cpu_device, I80188, i80188, "Intel 80188")
DEFINE_ZBC(i8031_device, I8031, i8031, "Intel 8031")
DEFINE_ZBC(i8032_device, I8032, i8032, "Intel 8032")
DEFINE_ZBC(i8035_device, I8035, i8035, "Intel 8035")
DEFINE_ZBC(i8039_device, I8039, i8039, "Intel 8039")
DEFINE_ZBC(i8040_device, I8040, i8040, "Intel 8040")
DEFINE_ZBC(i8080_cpu_device, I8080, i8080, "Intel 8080")
DEFINE_ZBC(i8080a_cpu_device, I8080A, i8080a, "Intel 8080A")
DEFINE_ZBC(i8085a_cpu_device, I8085A, i8085a, "Intel 8085A")
DEFINE_ZBC(i8086_cpu_device, I8086, i8086, "Intel 8086")
DEFINE_ZBC(i8088_cpu_device, I8088, i8088, "Intel 8088")
DEFINE_ZBC(i80c32_device, I80C32, i80c32, "Intel 80C32")
DEFINE_ZBC(i80c51gb_device, I80C51GB, i80c51gb, "Intel 80C51GB")
DEFINE_ZBC(i8344_device, I8344, i8344, "Intel 8344AH RUPI-44")
DEFINE_ZBC(i860_cpu_device, I860, i860xr, "Intel i860XR")
DEFINE_ZBC(igs036_cpu_device, IGS036, igs036, "IGS036")
DEFINE_ZBC(scmp_device, SCMP, ins8050, "National Semiconductor ISP-8A/500D SC/MP")
DEFINE_ZBC(ins8060_device, INS8060, ins8060, "National Semiconductor INS 8060 SC/MP II")
DEFINE_ZBC(k1801vm1_device, K1801VM1, k1801vm1, "K1801VM1")
DEFINE_ZBC(k1801vm2_device, K1801VM2, k1801vm2, "K1801VM2")
DEFINE_ZBC(konami_cpu_device, KONAMI, konami_cpu, "KONAMI CPU")
DEFINE_ZBC(lsi11_device, LSI11, lsi11, "DEC LSI-11")
DEFINE_ZBC(m37450_device, M37450, m37450, "Mitsubishi M37450")
DEFINE_ZBC(m37702s1_device, M37702S1, m37702s1, "Mitsubishi M37702S1")
DEFINE_ZBC(m37710s4_device, M37710S4, m37710s4, "Mitsubishi M37710S4")
DEFINE_ZBC(m37720s1_device, M37720S1, m37720s1, "Mitsubishi M37720S1")
DEFINE_ZBC(m37730s2_device, M37730S2, m37730s2, "Mitsubishi M37730S2")
DEFINE_ZBC(m37732s4_device, M37732S4, m37732s4, "Mitsubishi M37732S4")
DEFINE_ZBC(m4510_device, M4510, m4510, "CSG 4510")
DEFINE_ZBC(m6502_device, M6502, m6502, "MOS Technology 6502")
DEFINE_ZBC(m6503_device, M6503, m6503, "MOS Technology 6503")
DEFINE_ZBC(m6504_device, M6504, m6504, "MOS Technology 6504")
DEFINE_ZBC(m6508_device, M6508, m6508, "MOS Technology 6508")
DEFINE_ZBC(m6509_device, M6509, m6509, "MOS Technology 6509")
DEFINE_ZBC(m6510_device, M6510, m6510, "MOS Technology 6510")
DEFINE_ZBC(m6510t_device, M6510T, m6510t, "MOS Technology 6510T")
DEFINE_ZBC(m6512_device, M6512, m6512, "MOS Technology 6512")
DEFINE_ZBC(m65ce02_device, M65CE02, m65ce02, "CSG 65CE02")
DEFINE_ZBC(m6800_cpu_device, M6800, m6800, "Motorola MC6800")
DEFINE_ZBC(m68000_device, M68000, m68000, "Motorola MC68000")
DEFINE_ZBC(m68008_device, M68008, m68008, "Motorola MC68008")
DEFINE_ZBC(m68008fn_device, M68008FN, m68008fn, "Motorola MC68008FN")
DEFINE_ZBC(m68010_device, M68010, m68010, "Motorola MC68010")
DEFINE_ZBC(m6802_cpu_device, M6802, m6802, "Motorola MC6802")
DEFINE_ZBC(m68020_device, M68020, m68020, "Motorola MC68020")
DEFINE_ZBC(m68020fpu_device, M68020FPU, m68020fpu, "Motorola MC68020FPU")
DEFINE_ZBC(m68020hmmu_device, M68020HMMU, m68020hmmu, "Motorola MC68020HMMU")
DEFINE_ZBC(m68020pmmu_device, M68020PMMU, m68020pmmu, "Motorola MC68020PMMU")
DEFINE_ZBC(m6803_cpu_device, M6803, m6803, "Motorola MC6803")
DEFINE_ZBC(m68030_device, M68030, m68030, "Motorola MC68030")
DEFINE_ZBC(m6803e_cpu_device, M6803E, m6803e, "Motorola MC6803E")
DEFINE_ZBC(m68040_device, M68040, m68040, "Motorola MC68040")
DEFINE_ZBC(m6808_cpu_device, M6808, m6808, "Motorola MC6808")
DEFINE_ZBC(m6809_device, M6809, m6809, "MC6809 (legacy)")
DEFINE_ZBC(m68ec020_device, M68EC020, m68ec020, "Motorola MC68EC020")
DEFINE_ZBC(m68ec030_device, M68EC030, m68ec030, "Motorola MC68EC030")
DEFINE_ZBC(m68ec040_device, M68EC040, m68ec040, "Motorola MC68EC040")
DEFINE_ZBC(m68hc05eg_device, M68HC05EG, m68hc05eg, "Motorola MC68HC05EG")
DEFINE_ZBC(m68lc040_device, M68LC040, m68lc040, "Motorola MC68LC040")
DEFINE_ZBC(m7501_device, M7501, m7501, "MOS Technology 7501")
DEFINE_ZBC(m8502_device, M8502, m8502, "MOS Technology 8502")
DEFINE_ZBC(mb86233_device, MB86233, mb86233, "Fujitsu MB86233 (TGP)")
DEFINE_ZBC(mb86234_device, MB86234, mb86234, "Fujitsu MB86234 (TGP)")
DEFINE_ZBC(mb86930_device, MB86930, mb86930, "Fujitsu MB86930 'SPARClite'")
DEFINE_ZBC(mb8884_device, MB8884, mb8884, "Fujitsu MB8884")
DEFINE_ZBC(mc6809_device, MC6809, mc6809, "Motorola MC6809")
DEFINE_ZBC(mc6809e_device, MC6809E, mc6809e, "Motorola MC6809E")
DEFINE_ZBC(mc68121_device, MC68121, mc68121, "Motorola MC68121 IPC")
DEFINE_ZBC(mc68hc11a1_device, MC68HC11A1, mc68hc11a1, "Motorola MC68HC11A1")
DEFINE_ZBC(mc68hc11d0_device, MC68HC11D0, mc68hc11d0, "Motorola MC68HC11D0")
DEFINE_ZBC(mc68hc11e1_device, MC68HC11E1, mc68hc11e1, "Motorola MC68HC11E1")
DEFINE_ZBC(mc68hc11f1_device, MC68HC11F1, mc68hc11f1, "Motorola MC68HC11F1")
DEFINE_ZBC(mc68hc11k1_device, MC68HC11K1, mc68hc11k1, "Motorola MC68HC11K1")
DEFINE_ZBC(mc68hc11m0_device, MC68HC11M0, mc68hc11m0, "Motorola MC68HC11M0")
DEFINE_ZBC(mc68hc811e2_device, MC68HC811E2, mc68hc811e2, "Motorola MC68HC811E2")
DEFINE_ZBC(mc88100_device, MC88100, mc88100, "Motorola MC88100")
DEFINE_ZBC(mcf5206e_device, MCF5206E, mcf5206e, "Freescale MCF5206E")
DEFINE_ZBC(mediagx_device, MEDIAGX, mediagx, "Cyrix MediaGX")
DEFINE_ZBC(mn1880_device, MN1880, mn1880, "Panasonic MN1880")
DEFINE_ZBC(mn18801a_device, MN18801A, mn18801a, "Panasonic MN18801A")
DEFINE_ZBC(mpc8240_device, MPC8240, mpc8240, "IBM PowerPC MPC8240")
DEFINE_ZBC(nios2_device, NIOS2, nios2, "Altera Nios II Processor")
DEFINE_ZBC(ns32008_device, NS32008, ns32008, "National Semiconductor NS32008")
DEFINE_ZBC(ns32016_device, NS32016, ns32016, "National Semiconductor NS32016")
DEFINE_ZBC(ns32032_device, NS32032, ns32032, "National Semiconductor NS32032")
DEFINE_ZBC(ns32332_device, NS32332, ns32332, "National Semiconductor NS32332")
DEFINE_ZBC(ns32532_device, NS32532, ns32532, "National Semiconductor NS32532")
DEFINE_ZBC(nsc800_device, NSC800, nsc800, "National Semiconductor NSC800")
DEFINE_ZBC(nsc8105_cpu_device, NSC8105, nsc8105, "NSC8105")
DEFINE_ZBC(pdp1_device, PDP1, pdp1_cpu, "DEC PDP-1 Central Processor")
DEFINE_ZBC(pdp8_device, PDP8, pdp8_cpu, "DEC PDP8")
DEFINE_ZBC(pentium_device, PENTIUM, pentium, "Intel Pentium")
DEFINE_ZBC(pentium2_device, PENTIUM2, pentium2, "Intel Pentium II")
DEFINE_ZBC(pentium3_device, PENTIUM3, pentium3, "Intel Pentium III")
DEFINE_ZBC(pentium4_device, PENTIUM4, pentium4, "Intel Pentium 4")
DEFINE_ZBC(pentium_mmx_device, PENTIUM_MMX, pentium_mmx, "Intel Pentium MMX")
DEFINE_ZBC(pentium_pro_device, PENTIUM_PRO, pentium_pro, "Intel Pentium Pro")
DEFINE_ZBC(pps4_device, PPS4, pps4, "Rockwell PPS4-4")
DEFINE_ZBC(pps4_2_device, PPS4_2, pps4_2, "Rockwell PPS-4/2")
DEFINE_ZBC(pxa250_cpu_device, PXA250, pxa250, "Intel XScale PXA250")
DEFINE_ZBC(pxa255_cpu_device, PXA255, pxa255, "Intel XScale PXA255")
DEFINE_ZBC(pxa270_cpu_device, PXA270, pxa270, "Intel XScale PXA270")
DEFINE_ZBC(qed5271be_device, QED5271BE, qed5271be, "MIPS QED5271 (big)")
DEFINE_ZBC(qed5271le_device, QED5271LE, qed5271le, "MIPS QED5271 (little)")
DEFINE_ZBC(r2000_device, R2000, r2000, "MIPS R2000")
DEFINE_ZBC(r2000a_device, R2000A, r2000a, "MIPS R2000A")
DEFINE_ZBC(r3000_device, R3000, r3000, "MIPS R3000")
DEFINE_ZBC(r3000a_device, R3000A, r3000a, "MIPS R3000A")
DEFINE_ZBC(r3041_device, R3041, r3041, "IDT R3041")
DEFINE_ZBC(r3051_device, R3051, r3051, "IDT R3051")
DEFINE_ZBC(r3052_device, R3052, r3052, "IDT R3052")
DEFINE_ZBC(r3052e_device, R3052E, r3052e, "IDT R3052E")
DEFINE_ZBC(r3071_device, R3071, r3071, "IDT R3071")
DEFINE_ZBC(r3081_device, R3081, r3081, "IDT R3081")
DEFINE_ZBC(r4000be_device, R4000BE, r4000be, "MIPS R4000 (big)")
DEFINE_ZBC(r4000le_device, R4000LE, r4000le, "MIPS R4000 (little)")
DEFINE_ZBC(r4400be_device, R4400BE, r4400be, "MIPS R4400 (big)")
DEFINE_ZBC(r4400le_device, R4400LE, r4400le, "MIPS R4400 (little)")
DEFINE_ZBC(r4600be_device, R4600BE, r4600be, "MIPS R4600 (big)")
DEFINE_ZBC(r4600le_device, R4600LE, r4600le, "MIPS R4600 (little)")
DEFINE_ZBC(r4650be_device, R4650BE, r4650be, "MIPS IDT R4650 (big)")
DEFINE_ZBC(r4650le_device, R4650LE, r4650le, "MIPS IDT R4650 (little)")
DEFINE_ZBC(r4700be_device, R4700BE, r4700be, "MIPS R4700 (big)")
DEFINE_ZBC(r4700le_device, R4700LE, r4700le, "MIPS R4700 (little)")
DEFINE_ZBC(r5000be_device, R5000BE, r5000be, "MIPS R5000 (big)")
DEFINE_ZBC(r5000le_device, R5000LE, r5000le, "MIPS R5000 (little)")
DEFINE_ZBC(r65c02_device, R65C02, r65c02, "Rockwell R65C02")
DEFINE_ZBC(r65c102_device, R65C102, r65c102, "Rockwell R65C102")
DEFINE_ZBC(r65c112_device, R65C112, r65c112, "Rockwell R65C112")
DEFINE_ZBC(rm7000be_device, RM7000BE, rm7000be, "MIPS RM7000 (big)")
DEFINE_ZBC(rm7000le_device, RM7000LE, rm7000le, "MIPS RM7000 (little)")
DEFINE_ZBC(rp2a03_device, RP2A03, rp2a03, "Ricoh RP2A03")
DEFINE_ZBC(rp2a03_core_device, RP2A03_CORE, rp2a03_core, "Ricoh RP2A03 core")
DEFINE_ZBC(rp2a03g_device, RP2A03G, rp2a03g, "Ricoh RP2A03G")
DEFINE_ZBC(rsp_device, RSP, rsp, "Nintendo & SGI Reality Signal Processor RSP")
DEFINE_ZBC(s2650_device, S2650, s2650, "Signetics 2650")
DEFINE_ZBC(sa1100_cpu_device, SA1100, sa1100, "Intel StrongARM SA-1100")
DEFINE_ZBC(sa1110_cpu_device, SA1110, sa1110, "Intel StrongARM SA-1110")
DEFINE_ZBC(saturn_device, SATURN, saturn_cpu, "Hewlett-Packard Saturn")
DEFINE_ZBC(sc61860_device, SC61860, sc61860, "Sharp SC61860")
DEFINE_ZBC(sh4_device, SH4, sh4, "Hitachi SH-4 (Unidentified)")
DEFINE_ZBC(sh7091_device, SH7091, sh7091, "Hitachi SH7091")
DEFINE_ZBC(sh7750_device, SH7750, sh7750, "Hitachi SH7750")
DEFINE_ZBC(sh7750r_device, SH7750R, sh7750r, "Hitachi SH7750R")
DEFINE_ZBC(sh7750s_device, SH7750S, sh7750s, "Hitachi SH7750S")
DEFINE_ZBC(sh7751_device, SH7751, sh7751, "Hitachi SH7751")
DEFINE_ZBC(sh7751r_device, SH7751R, sh7751r, "Hitachi SH7751R")
DEFINE_ZBC(iop_device, SONYPS2_IOP, sonyiop, "Sony Playstation 2 IOP")
DEFINE_ZBC(sparcv7_device, SPARCV7, sparcv7, "Sun SPARC v7")
DEFINE_ZBC(sparcv8_device, SPARCV8, sparcv8, "Sun SPARC v8")
DEFINE_ZBC(spc700_device, SPC700, spc700, "Sony SPC700")
DEFINE_ZBC(st2202_device, ST2202, st2202, "Sitronix ST2202 Integrated Microcontroller")
DEFINE_ZBC(st2204_device, ST2204, st2204, "Sitronix ST2204 Integrated Microcontroller")
DEFINE_ZBC(st2205u_device, ST2205U, st2205u, "Sitronix ST2205U Integrated Microcontroller")
DEFINE_ZBC(st2302u_device, ST2302U, st2302u, "Sitronix ST2302U Integrated Microcontroller")
DEFINE_ZBC(t11_device, T11, t11, "DEC T11")
DEFINE_ZBC(tmp90841_device, TMP90841, tmp90841, "Toshiba TMP90841")
DEFINE_ZBC(tmp90845_device, TMP90845, tmp90845, "Toshiba TMP90845")
DEFINE_ZBC(tmp91641_device, TMP91641, tmp91641, "Toshiba TMP91641")
DEFINE_ZBC(tmp95c061_device, TMP95C061, tmp95c061, "Toshiba TMP95C061")
DEFINE_ZBC(tmp95c063_device, TMP95C063, tmp95c063, "Toshiba TMP95C063")
DEFINE_ZBC(tms34010_device, TMS34010, tms34010, "Texas Instruments TMS34010")
DEFINE_ZBC(tms34020_device, TMS34020, tms34020, "Texas Instruments TMS34020")
DEFINE_ZBC(tms7000_device, TMS7000, tms7000, "Texas Instruments TMS7000")
DEFINE_ZBC(tms7001_device, TMS7001, tms7001, "Texas Instruments TMS7001")
DEFINE_ZBC(tms7002_device, TMS7002, tms7002, "Texas Instruments TMS7002")
DEFINE_ZBC(tms70c00_device, TMS70C00, tms70c00, "Texas Instruments TMS70C00")
DEFINE_ZBC(tms9900_device, TMS9900, tms9900, "Texas Instruments TMS9900")
DEFINE_ZBC(tms9980a_device, TMS9980A, tms9980a, "Texas Instruments TMS9980A")
DEFINE_ZBC(tms9981_device, TMS9981, tms9981, "Texas Instruments TMS9981")
DEFINE_ZBC(tms9995_device, TMS9995, tms9995, "Texas Instruments TMS9995")
DEFINE_ZBC(tx4925be_device, TX4925BE, tx4925be, "Toshiba TX4925 (big)")
DEFINE_ZBC(tx4925le_device, TX4925LE, tx4925le, "Toshiba TX4925 (little)")
DEFINE_ZBC(upd7725_device, UPD7725, upd7725, "NEC uPD7725")
DEFINE_ZBC(upd7807_device, UPD7807, upd7807, "NEC uPD7807")
DEFINE_ZBC(upd7810_device, UPD7810, upd7810, "NEC uPD7810")
DEFINE_ZBC(upd78c05_device, UPD78C05, upd78c05, "NEC uPD78C05")
DEFINE_ZBC(upd78c10_device, UPD78C10, upd78c10, "NEC uPD78C10")
DEFINE_ZBC(upd96050_device, UPD96050, upd96050, "NEC uPD96050")
DEFINE_ZBC(v20_device, V20, v20, "NEC V20")
DEFINE_ZBC(v25_device, V25, v25, "NEC V25")
DEFINE_ZBC(v30_device, V30, v30, "NEC V30")
DEFINE_ZBC(v33_device, V33, v33, "NEC V33")
DEFINE_ZBC(v33a_device, V33A, v33a, "NEC V33A")
DEFINE_ZBC(v35_device, V35, v35, "NEC V35")
DEFINE_ZBC(v40_device, V40, v40, "NEC V40")
DEFINE_ZBC(v50_device, V50, v50, "NEC V50")
DEFINE_ZBC(v53_device, V53, v53, "NEC V53")
DEFINE_ZBC(v53a_device, V53A, v53a, "NEC V53A")
DEFINE_ZBC(v810_device, V810, v810, "NEC V810")
DEFINE_ZBC(vr4300be_device, VR4300BE, vr4300be, "NEC VR4300 (big)")
DEFINE_ZBC(vr4300le_device, VR4300LE, vr4300le, "NEC VR4300 (little)")
DEFINE_ZBC(vr4310be_device, VR4310BE, vr4310be, "NEC VR4310 (big)")
DEFINE_ZBC(vr4310le_device, VR4310LE, vr4310le, "NEC VR4310 (little)")
DEFINE_ZBC(vr5500be_device, VR5500BE, vr5500be, "NEC VR5500 (big)")
DEFINE_ZBC(vr5500le_device, VR5500LE, vr5500le, "NEC VR5500 (little)")
DEFINE_ZBC(w65c02_device, W65C02, w65c02, "WDC W65C02")
DEFINE_ZBC(w65c02s_device, W65C02S, w65c02s, "WDC W65C02S")
DEFINE_ZBC(g65802_device, G65802, w65c802, "WDC W65C802")
DEFINE_ZBC(g65816_device, G65816, w65c816, "WDC W65C816")
DEFINE_ZBC(we32100_device, WE32100, we32100, "AT&T WE32100")
DEFINE_ZBC(xavix_device, XAVIX, xavix, "XaviX (SSD 97 / SSD 98)")
DEFINE_ZBC(xavix2_device, XAVIX2, xavix2, "Xavix 2 CPU")
DEFINE_ZBC(xavix2000_device, XAVIX2000, xavix2000, "XaviX (SSD 2000)")
DEFINE_ZBC(xavix2002_device, XAVIX2002, xavix2002, "XaviX (SSD 2002) (SuperXaviX)")
DEFINE_ZBC(z80_device, Z80, z80, "Zilog Z80")
DEFINE_ZBC(z8001_device, Z8001, z8001, "Zilog Z8001")
DEFINE_ZBC(z8002_device, Z8002, z8002, "Zilog Z8002")
DEFINE_ZBC(z80180_device, Z80180, z80180, "Zilog Z80180")
DEFINE_ZBC(z80182_device, Z80182, z80182, "Zilog Z80182")
DEFINE_ZBC(z8681_device, Z8681, z8681, "Zilog Z8681")
DEFINE_ZBC(z8s180_device, Z8S180, z8s180, "Zilog Z8S180")

// CPUs with Missing Headers (7)
// These CPUs are commented out because their header files could not be found
// Fix the header_file path in zbc_status.csv and regenerate

// DEFINE_ZBC(tms32010_device, TMS32010, tms32010, "Texas Instruments TMS32010")
//   Header not found: cpu/tms32010/tms32010.h

// DEFINE_ZBC(tms32015_device, TMS32015, tms32015, "Texas Instruments TMS32015")
//   Header not found: cpu/tms32010/tms32010.h

// DEFINE_ZBC(tms32016_device, TMS32016, tms32016, "Texas Instruments TMS32016")
//   Header not found: cpu/tms32010/tms32010.h

// DEFINE_ZBC(tms32020_device, TMS32020, tms32020, "Texas Instruments TMS32020")
//   Header not found: cpu/tms32025/tms32025.h

// DEFINE_ZBC(tms32025_device, TMS32025, tms32025, "Texas Instruments TMS32025")
//   Header not found: cpu/tms32025/tms32025.h

// DEFINE_ZBC(tms32026_device, TMS32026, tms32026, "Texas Instruments TMS32026")
//   Header not found: cpu/tms32025/tms32025.h

// DEFINE_ZBC(tms32082_pp_device, TMS32082_PP, tms32082_pp, "Texas Instruments TMS32082 PP")
//   Header not found: cpu/tms32082/tms32082.h

// Broken/Disabled CPUs (121)
// These CPUs are commented out due to compilation or validation issues

// DEFINE_ZBC(am8753_device, AM8753, am8753, "AMD Am8753")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(am9517a_device, AM9517A, am9517a, "AM9517A")
//   Status: not_cpu
//   Notes: DMA controller

// DEFINE_ZBC(at89c52_device, AT89C52, at89c52, "Atmel AT89C52")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(at89s52_device, AT89S52, at89s52, "Atmel AT89S52")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(cxd8530aq_device, CXD8530AQ, cxd8530aq, "Sony CXD8530AQ")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(cxd8530bq_device, CXD8530BQ, cxd8530bq, "Sony CXD8530BQ")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(cxd8530cq_device, CXD8530CQ, cxd8530cq, "Sony CXD8530CQ")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(cxd8606bq_device, CXD8606BQ, cxd8606bq, "Sony CXD8606BQ")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(cxd8606cq_device, CXD8606CQ, cxd8606cq, "Sony CXD8606CQ")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(cxd8661r_device, CXD8661R, cxd8661r, "Sony CXD8661R")
//   Status: broken_validate
//   Notes: Crashes during validation

// DEFINE_ZBC(dsp32c_device, DSP32C, dsp32c, "AT&T DSP32C")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(dsp56303_device, DSP56303, dsp56303, "Motorola DSP56303")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(eisa_dma_device, EISA_DMA, eisa_dma, "EISA DMA")
//   Status: not_cpu
//   Notes: DMA controller

// DEFINE_ZBC(hd6301v1_cpu_device, HD6301V1, hd6301v1, "Hitachi HD6301V1")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd6301x0_cpu_device, HD6301X0, hd6301x0, "Hitachi HD6301X0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd6301y0_cpu_device, HD6301Y0, hd6301y0, "Hitachi HD6301Y0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd6303x_cpu_device, HD6303X, hd6303x, "Hitachi HD6303X")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(hd6303y_cpu_device, HD6303Y, hd6303y, "Hitachi HD6303Y")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(hd63701v0_cpu_device, HD63701V0, hd63701v0, "Hitachi HD63701V0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd63701x0_cpu_device, HD63701X0, hd63701x0, "Hitachi HD63701X0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd63701y0_cpu_device, HD63701Y0, hd63701y0, "Hitachi HD63701Y0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(hd6801v0_cpu_device, HD6801V0, hd6801v0, "Hitachi HD6801V0")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8021_device, I8021, i8021, "Intel 8021")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8022_device, I8022, i8022, "Intel 8022")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i80286_cpu_device, I80286, i80286, "Intel 80286")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -9 (exit -9)

// DEFINE_ZBC(i8041a_device, I8041A, i8041a, "Intel 8041A")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8041ah_device, I8041AH, i8041ah, "Intel 8041AH")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8042_device, I8042, i8042, "Intel 8042")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8042ah_device, I8042AH, i8042ah, "Intel 8042AH")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8048_device, I8048, i8048, "Intel 8048")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8049_device, I8049, i8049, "Intel 8049")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8050_device, I8050, i8050, "Intel 8050")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8051_device, I8051, i8051, "Intel 8051")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8052_device, I8052, i8052, "Intel 8052")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i80960ka_device, I80960KA, i80960ka, "Intel 80960KA")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(i80960kb_device, I80960KB, i80960kb, "Intel 80960KB")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(i80c52_device, I80C52, i80c52, "Intel 80C52")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8648_device, I8648, i8648, "Intel 8648")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8741a_device, I8741A, i8741a, "Intel 8741A")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8741ah_device, I8741AH, i8741ah, "Intel 8741AH")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8742_device, I8742, i8742, "Intel 8742")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8742ah_device, I8742AH, i8742ah, "Intel 8742AH")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8744_device, I8744, i8744, "Intel 8744H RUPI-44")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8748_device, I8748, i8748, "Intel 8748")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8749_device, I8749, i8749, "Intel 8749")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(i8751_device, I8751, i8751, "Intel 8751")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i8752_device, I8752, i8752, "Intel 8752")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i87c51fa_device, I87C51FA, i87c51fa, "Intel 87C51FA")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(i87c52_device, I87C52, i87c52, "Intel 87C52")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m37702m2_device, M37702M2, m37702m2, "Mitsubishi M37702M2")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m50740_device, M50740, m50740, "Mitsubishi M50740")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m50741_device, M50741, m50741, "Mitsubishi M50741")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m50753_device, M50753, m50753, "Mitsubishi M50753")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m58715_device, M58715, m58715, "Mitsubishi M58715")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(m6801_cpu_device, M6801, m6801, "Motorola MC6801")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(m6801u4_cpu_device, M6801U4, m6801u4, "Motorola MC6801U4")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(mb86235_device, MB86235, mb86235, "Fujitsu MB86235 'TGPx4'")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(mc68120_device, MC68120, mc68120, "Motorola MC68120 IPC")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(pcxport_dmac_device, PCXPORT_DMAC, pcx_dmac, "PC Transporter DMAC")
//   Status: not_cpu
//   Notes: DMA controller

// DEFINE_ZBC(ppc403ga_device, PPC403GA, ppc403ga, "IBM PowerPC 403GA")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc403gcx_device, PPC403GCX, ppc403gcx, "IBM PowerPC 403GCX")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc405gp_device, PPC405GP, ppc405gp, "IBM PowerPC 405GP")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc601_device, PPC601, ppc601, "IBM PowerPC 601")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc602_device, PPC602, ppc602, "IBM PowerPC 602")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc603_device, PPC603, ppc603, "IBM PowerPC 603")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc603e_device, PPC603E, ppc603e, "IBM PowerPC 603E")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc603r_device, PPC603R, ppc603r, "IBM PowerPC 603R")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc604_device, PPC604, ppc604, "IBM PowerPC 604")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc740_device, PPC740, ppc740, "IBM PowerPC 740")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ppc750_device, PPC750, ppc750, "IBM PowerPC 750")
//   Status: broken_drc
//   Notes: DRC static handlers cause infinite loop

// DEFINE_ZBC(ps2_gif_device, SONYPS2_GIF, ps2gif, "Playstation 2 GIF")
//   Status: not_cpu
//   Notes: Graphics Interface

// DEFINE_ZBC(ps2_vif1_device, SONYPS2_VIF1, ps2vif1, "PlayStation 2 VIF1")
//   Status: not_cpu
//   Notes: Video Interface

// DEFINE_ZBC(r5900be_device, R5900BE, r5900be, "Emotion Engine Core (big)")
//   Status: needs_dependent_device
//   Notes: Requires additional dependent devices

// DEFINE_ZBC(r5900le_device, R5900LE, r5900le, "Emotion Engine Core (little)")
//   Status: needs_dependent_device
//   Notes: Requires additional dependent devices

// DEFINE_ZBC(sh3_device, SH3, sh3, "Hitachi SH-3 (Unidentified)")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(sh7708s_device, SH7708S, sh7708s, "Hitachi SH7708S")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(sh7709_device, SH7709, sh7709, "Hitachi SH7709")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(sh7709s_device, SH7709S, sh7709s, "Hitachi SH7709S")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(sonyvu0_device, SONYPS2_VU0, sonyvu0, "Sony PlayStation 2 VU0")
//   Status: needs_dependent_device
//   Notes: Requires additional dependent devices

// DEFINE_ZBC(sonyvu1_device, SONYPS2_VU1, sonyvu1, "Sony PlayStation 2 VU1")
//   Status: needs_dependent_device
//   Notes: Requires additional dependent devices

// DEFINE_ZBC(tmp90840_device, TMP90840, tmp90840, "Toshiba TMP90840")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tmp90ph44_device, TMP90PH44, tmp90ph44, "Toshiba TMP90PH44")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tmp91640_device, TMP91640, tmp91640, "Toshiba TMP91640")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms32030_device, TMS32030, tms32030, "Texas Instruments TMS320C30")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(tms32031_device, TMS32031, tms32031, "Texas Instruments TMS320C31")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(tms32032_device, TMS32032, tms32032, "Texas Instruments TMS320C32")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(tms32033_device, TMS32033, tms32033, "Texas Instruments TMS320VC33")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(tms32051_device, TMS32051, tms32051, "Texas Instruments TMS32051")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(tms32053_device, TMS32053, tms32053, "Texas Instruments TMS32053")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(tms32082_mp_device, TMS32082_MP, tms32082_mp, "Texas Instruments TMS32082 MP")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(tms7020_device, TMS7020, tms7020, "Texas Instruments TMS7020")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms7020_exl_device, TMS7020_EXL, tms7020_exl, "Texas Instruments TMS7020 (Exelvision)")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms7040_device, TMS7040, tms7040, "Texas Instruments TMS7040")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms7041_device, TMS7041, tms7041, "Texas Instruments TMS7041")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms7042_device, TMS7042, tms7042, "Texas Instruments TMS7042")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms70c20_device, TMS70C20, tms70c20, "Texas Instruments TMS70C20")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms70c40_device, TMS70C40, tms70c40, "Texas Instruments TMS70C40")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms70c46_device, TMS70C46, tms70c46, "Texas Instruments TMS70C46")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(tms9995_mp9537_device, TMS9995_MP9537, tms9995_mp9537, "Texas Instruments TMS9995-MP9537")
//   Status: disabled
//   Notes: Driver name zbctms9995_mp9537 exceeds MAME 16-char limit

// DEFINE_ZBC(tx0_64kw_device, TX0_64KW, tx0_64kw_cpu, "MIT Lincoln Laboratory TX-0 64KW")
//   Status: disabled
//   Notes: Driver name zbctx0_64kw_cpu exceeds MAME 16-char limit

// DEFINE_ZBC(tx0_8kw_device, TX0_8KW, tx0_8kw_cpu, "MIT Lincoln Laboratory TX-0 8KW (new)")
//   Status: disabled
//   Notes: Driver name zbctx0_8kw_cpu exceeds MAME 16-char limit

// DEFINE_ZBC(tx0_8kwo_device, TX0_8KW_OLD, tx0_8kwo_cpu, "MIT Lincoln Laboratory TX-0 8KW (old)")
//   Status: disabled
//   Notes: Driver name zbctx0_8kwo_cpu exceeds MAME 16-char limit

// DEFINE_ZBC(ub8830d_device, UB8830D, ub8830d, "UB8830D")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(unsp_device, UNSP, unsp, "SunPlus u'nSP (ISA 1.0)")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -9 (exit -9)

// DEFINE_ZBC(unsp_11_device, UNSP_11, unsp_11, "SunPlus u'nSP (ISA 1.1)")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -9 (exit -9)

// DEFINE_ZBC(unsp_12_device, UNSP_12, unsp_12, "SunPlus u'nSP (ISA 1.2)")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -9 (exit -9)

// DEFINE_ZBC(unsp_20_device, UNSP_20, unsp_20, "SunPlus u'nSP (ISA 2.0)")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -9 (exit -9)

// DEFINE_ZBC(upd7751_device, UPD7751, upd7751, "NEC uPD7751")
//   Status: broken_validate
//   Notes: Test failed: Unknown error -11 (exit -11)

// DEFINE_ZBC(upd7801_device, UPD7801, upd7801, "NEC uPD7801")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(upd7811_device, UPD7811, upd7811, "NEC uPD7811")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(upd78c06_device, UPD78C06, upd78c06, "NEC uPD78C06")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(upd78c11_device, UPD78C11, upd78c11, "NEC uPD78C11")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(upd78c14_device, UPD78C14, upd78c14, "NEC uPD78C14")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(v5x_dmau_device, V5X_DMAU, v5x_dmau, "V5X DMAU")
//   Status: not_cpu
//   Notes: DMA unit

// DEFINE_ZBC(v60_device, V60, v60, "NEC V60")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(v70_device, V70, v70, "NEC V70")
//   Status: broken_validate
//   Notes: Test failed: Fatal error (exit 3)

// DEFINE_ZBC(z8601_device, Z8601, z8601, "Zilog Z8601")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(z8611_device, Z8611, z8611, "Zilog Z8611")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

// DEFINE_ZBC(z8671_device, Z8671, z8671, "Zilog Z8671")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(z8682_device, Z8682, z8682, "Zilog Z8682")
//   Status: broken_validate
//   Notes: Test failed: Missing files (exit 2)

// DEFINE_ZBC(z86e02_device, Z86E02, z86e02, "Zilog Z86E02")
//   Status: needs_internal_rom
//   Notes: Requires internal ROM/RAM regions not provided by ZBC

